apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
    namespace: default
type: Opaque
stringData:
    adminToken: ENC[AES256_GCM,data:dagfr6iOKmP6as3TiENNIqd6IdEw82ab47HC6/cHKlanEZ7jePkytK4emc7C8OK1tbIl8zakrIRJZaFOi1GmKg8ozx3Hn04S7JqMc1m+PbWa8kG2H2DtQX0=,iv:r+0hUZFX6zKxO8gZR6BrlWchnWqWRG7HlRirZ5oOVxQ=,tag:BJLQY6ay4jwgAqUjND1a+w==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:xiTWaa41HEhsh+brLGPtYySJ3gKI+k6bE2VQksbOjdNjLu8YLQCCu1KPFkcfBvPUfFlnf9RZlK5314wpYqaGxZec/UCCeA2JnenF3cNcVmSTboIdBD8=,iv:ygymNwXYXJhN+rxjknoqHMSWJKEyo1BL57Yw9UW0myI=,tag:ad+bc0HQZ4X/g7z8RYjA8g==,type:str]
    #ENC[AES256_GCM,data:tYc7Ssqv5koGooO0bI4=,iv:Nse5OUykz8GASQDHoIiGIEX1qouFGJgoxcomduToHyU=,tag:EyQ4YoqLkGqD2v7XfosRxg==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:ALLmPQiGz69jIXA=,iv:Nlw3/WxWU3YEK+dh16Ife8d+G5XMd2xDSgF7M8RSPoY=,tag:J+5/NTdLKHnFYfbBSCuEsA==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:q38E5OEaw2KU83GqFC+BW9zf0bp3Vhn3j4QhBgownXran0SSdrk60y5c,iv:boszSyZDovw5q7qAJbxiqr79eOUgrNvtePILUYOu7S8=,tag:3RxGHzzB/f/rZ0pXhP88vw==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:a58BpIB7og==,iv:Rc5PU16rQk7ASHhZIUEnsWqSMAkRwwKFLjm94wmOfaU=,tag:YrQDKflxtXwSIdgaiUZqvA==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:X4EiDiOJTQ==,iv:+FeXgl04CkYaCUIbe+CjKMFpn/v1rjVN7foJhy8O9Es=,tag:69hfuyLyGC76CwndjI1/Zg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:hYk7zzs=,iv:rf+u8y7Omt2Kk4IQTpeZYn5YNnGB66BWcp0EPLUdCwc=,tag:cJfBApUTO2uCIogMRKiG6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjQXZUZ3RXRHNsb1ZkcXNh
            OHdNU3JLdFhPQll0N0tqemg4eHVkM2p5aW5rClRTRVRLRks2c0lKd0RHTStmSEZa
            aEM2NXBrYTQ1bkxtN2tobmJXTGJGRlEKLS0tIFlVU1lJZkZ3YVh2aTUzK2YzUXdQ
            T0FmT2ZJRkN2eldrWGFZdTNnRkR4alEKpJtIpiuKI+sRwsgry4US+Ob41/VG1/Oh
            RHWpsTsP6PP4aT7OPIc9yWE2ecLZxuAmQ2xvKC6iUKCJb1e4xiPJCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-16T04:26:32Z"
    mac: ENC[AES256_GCM,data:y3d1SbF9O1PTEyD4Fbt4XTfLwdDav+f6/rfFYW3WFCQ3pM9f24RFW/jt/ZIqAwPAEGUzZSnQt2HkhoM5zTK2oV7oQGdkag3XgbPwmVfJWaFZJthysMrwR8Xfs98UnqJRHA5dWtIOFBtVJXKX0dGGvW5Oen0VFoXqQvtYsVIema0=,iv:Uq7Avj1Yz520QDTSTLAPcXyk7O3lP7KNQuYXCru4pzg=,tag:CJXgPEBevPQyJArGk79keg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-restic-secret
    namespace: default
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:N+drK58zEAqSWq75QD05F23Z3YrO7P9aI3QTmZsz9ICIimNds76HWbB4Ig==,iv:iqot20sVF2f09NtbFsgzq+FRa4j8bpFIAzPDonbIEAI=,tag:rKHbJr4HLqQgYxmLfG2tYA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:h4E7XTB39zZCArXj0k3N5cw=,iv:+a1Chdrc4Qr3+U8cLQnHmqeXUpIglK1FygTdtQyOGWo=,tag:rj/qWgb7vKz7B6NV8SZr7Q==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:10gkeu4OWnuE/OhM1Aa5tg==,iv:VjhHtoHiJ+n4J6IEUZ9WZY2Qo7BnmRwa86hwxPrNVSo=,tag:Ca7x5qLjoObGImWzRQdlew==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:V/4bJDGIpjJTjMpfiyYaP6XjXpSLAX8M8ot5mnvwbl213GqUu1P0Lg==,iv:efBhnEi4G1J7+7g1JLpqjeyrpH6gAPgmlsh5V2dzzIg=,tag:it95BDfCHnOOaaVZQeIqhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjQXZUZ3RXRHNsb1ZkcXNh
            OHdNU3JLdFhPQll0N0tqemg4eHVkM2p5aW5rClRTRVRLRks2c0lKd0RHTStmSEZa
            aEM2NXBrYTQ1bkxtN2tobmJXTGJGRlEKLS0tIFlVU1lJZkZ3YVh2aTUzK2YzUXdQ
            T0FmT2ZJRkN2eldrWGFZdTNnRkR4alEKpJtIpiuKI+sRwsgry4US+Ob41/VG1/Oh
            RHWpsTsP6PP4aT7OPIc9yWE2ecLZxuAmQ2xvKC6iUKCJb1e4xiPJCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-16T04:26:32Z"
    mac: ENC[AES256_GCM,data:y3d1SbF9O1PTEyD4Fbt4XTfLwdDav+f6/rfFYW3WFCQ3pM9f24RFW/jt/ZIqAwPAEGUzZSnQt2HkhoM5zTK2oV7oQGdkag3XgbPwmVfJWaFZJthysMrwR8Xfs98UnqJRHA5dWtIOFBtVJXKX0dGGvW5Oen0VFoXqQvtYsVIema0=,iv:Uq7Avj1Yz520QDTSTLAPcXyk7O3lP7KNQuYXCru4pzg=,tag:CJXgPEBevPQyJArGk79keg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
