---
# yaml-language-server: $schema=https://raw.githubusercontent.com/JJGadgets/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app snapshot-controller
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      chart: *app
      version: 2.1.0
      sourceRef:
        kind: HelmRepository
        name: piraeus
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5
  values:
    volumeSnapshotClasses:
      - name: csi-ceph-blockpool
        driver: rook-ceph.rbd.csi.ceph.com
        annotations:
          snapshot.storage.kubernetes.io/is-default-class: "false"
        parameters:
          clusterID: rook-ceph
          csi.storage.k8s.io/snapshotter-secret-name: rook-csi-rbd-provisioner
          csi.storage.k8s.io/snapshotter-secret-namespace: rook-ceph
        deletionPolicy: Delete
      - name: csi-hostpath-snapclass
        driver: hostpath.csi.k8s.io
        annotations:
          snapshot.storage.kubernetes.io/is-default-class: "true"
        parameters:
        deletionPolicy: Delete
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - node-3
                    - worker-1
