---
apiVersion: v1
kind: Service
metadata:
  name: postgres-lb
  namespace: database
  annotations:
    "io.cilium/lb-ipam-ips": "192.168.1.203"
#    coredns.io/hostname: "postgres-v15.${SECRET_DOMAIN}"
spec:
  type: LoadBalancer
#  externalTrafficPolicy: Local
#  externalIPs: ["192.168.1.203"]
  loadBalancerIP: "192.168.1.203"
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres-v15
    role: primary
