---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-home-assistant
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-nginx-external
    - name: cluster-apps-rook-ceph-cluster
    - name: cluster-apps-volsync
    - name: cluster-apps-cloudnative-pg
  path: ./kubernetes/apps/home-automation/home-assistant/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: home-assistant
      namespace: home-automation
  interval: 30m
  retryInterval: 1m
  timeout: 10m

---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-ha-chris
  namespace: flux-system
spec:
  dependsOn:

    - name: cluster-apps-nginx-external
    - name: cluster-apps-rook-ceph-cluster
    - name: cluster-apps-volsync
    - name: cluster-apps-cloudnative-pg
  path: ./kubernetes/apps/home-automation/home-assistant/app-chris
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: ha-chris
      namespace: home-automation
  interval: 30m
  retryInterval: 1m
  timeout: 10m
