apiVersion: v1
kind: Secret
metadata:
    name: solectrus-secret
    namespace: observability
type: Opaque
stringData:
    APP_HOST: ENC[AES256_GCM,data:ohZZtX28tsCuKx6DbsDv5ItkMuR8ysKu/lY=,iv:ExEw3YPBI+NZzuRxrG4K3jskXZr3FxbYF5TQ3kFU7XY=,tag:z0GmMCTILTYPXvGOrm48IA==,type:str]
    FORCE_SSL: ENC[AES256_GCM,data:QfzJ8DM=,iv:3OT76NKTlABfuqlBjDMKjmHp/jAr5Wqb8j0a3aESKaI=,tag:K7PvTnHaAZEfw+KE+DWsHQ==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:roZ5r8cOYDP76s7kwyZN7dEfIv/TOXsplt5k4WcGjmTyUcimkWPGP3F1J9+EgDAgPtGLYW3Azk973tG6grmIVODs1lTRx5PZuc/Sv0w2zvPHQnw5Z1J6asLoCTsQRMd4Qb5jvsm4gBwqBjgMSS4P+hpLUP/zdaIhW8Vo17+DOeq5NL+citQuJFkOG1dr3rlmOWFGEpAFwCSeRgTXfg62laE7lbb2EsPrm/XimzG/2xyfxPF1e6dtnSrxu/nxJVt1GfiB04mkyJDXOSGZvQaqKyP/u2S86fQ6BTpG94G9NMnJf3EMLfqX+Zi/ekcdA2DhM3tpOcqvGgIe2P5AXgERrA==,iv:W+Zg9FCVKiE2lOl1JbQa9ejYz3AzFwJKGBKvytfgelw=,tag:MNiPyG7i9xvVxoRVYyz2+A==,type:str]
    INSTALLATION_DATE: ENC[AES256_GCM,data:u8yK8vzqHLrFNw==,iv:WJlMjpgeylLhuGq3NLi3uvYeCgUDu3CWjDUrH4OZdGI=,tag:qwlH4K9IeFp01s3+TWvk+g==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:TB0wYtqm772WR7rltvyWQEA=,iv:qQA7yRHKQrPQS5hl8HnFewb1dCBwE8y5qqyopXQDKL4=,tag:rDNrd42pHWPe8H7f9fXVSQ==,type:str]
    INFLUX_ORG: ENC[AES256_GCM,data:3YfaxgGQkdsXcA==,iv:IKlnAqdl+OmhBeK7RK6ofgvnNqS6gZJtvuXk95GOrMo=,tag:XVsZp9BYTZ+OCQjV01Cqgw==,type:str]
    INFLUX_HOST: ENC[AES256_GCM,data:YuZnAYllXkm2Nd7Fh4XDyfaFOzalV669KEgcYj7VSJilaHctCb6YBYN0IDFd90zwkGU=,iv:c+0LVjW3HKb66N/s+DEEkB24KxWH0wPKZ2TByC4hybA=,tag:2K7JJTdcnW9CGZiNNWcSFg==,type:str]
    INFLUX_PORT: ENC[AES256_GCM,data:bEs=,iv:NuV7UJZlqM7syY0K1FxpMHaVX6AOco6IyQhy9tC0wUk=,tag:vU+H+CjzxbvbGvaHk9Qm5g==,type:int]
    INFLUX_TOKEN: ENC[AES256_GCM,data:XNB/HE9VItxzCAsdpb3jS24xk+UqYn5K/YJyEmGsaR8Pgc6rTjEE9pG7vpWxHQ6uUulAJA1rA3gV282XB529T3WYEY4ka9x9F3Jz3fg9Qd2br7KFWqvq2Q==,iv:VmlYnGH5tbIiJIyxkpEpmflTdSwrE+ov6g1+Zwv5sAg=,tag:Dfb2D6BTFNicI3sL3Zhdug==,type:str]
    INFLUX_BUCKET: ENC[AES256_GCM,data:syxSYWd/tQSC,iv:LMx5iKDhv19YQcBr2NZ2WvdF05G0KVjr7LaiYn0CnGM=,tag:6pw15hXJy27iQz68FYZKTg==,type:str]
    INFLUX_MEASUREMENT_PV: ENC[AES256_GCM,data:hs9vhrw3Lom7Dv8qmAN22Pw=,iv:4P4vTsEk7xpjzivOas+xtc/Zr2QL6oUoiiW/IPKkNfY=,tag:06gWoIaR2u9cFdyK57DIEA==,type:str]
    INFLUX_MEASUREMENT_FORECAST: ENC[AES256_GCM,data:qRIpl8jxW+o=,iv:iHrWotJ2MCJz1Slb5PPNrrjRxanYmmoXXkRQovIJsok=,tag:5X8lJ1d/EuQLmH/yc8ym7g==,type:str]
    INFLUX_POLL_INTERVAL: ENC[AES256_GCM,data:8g==,iv:qmGI4QQrJKjcra36VnFZBVu70GS1Fik99Arrme1pFx8=,tag:l/0w1R4b1ye5Q8Z4vAx5vw==,type:str]
    WEB_CONCURRENCY: ENC[AES256_GCM,data:pw==,iv:HD0gA4rW4MWyT3JKGjklzhH50i745fCbrEoYaPtK5FM=,tag:5jeqrWJJSKWkYaCXR5fX0w==,type:str]
    FRAME_ANCESTORS: ""
    DB_HOST: ENC[AES256_GCM,data:B4EuAEBsw7BAiIr3exM9ynCLZydUmAPkJCyp+v75o8izYVPgNDtHiICC,iv:aVuMGt9tEzWC0qs6rJxyAqaQz25y1HrP846suKu3BMM=,tag:BRDoxUZ1C8CIi4S0WFe+6Q==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:jgr34SooNg==,iv:PkUHAPcDEL0xlT3mkg7ZJ+weKVNyfp3b8TjnT39APJU=,tag:FeEYtf1Vu3pU+m0G7dvD4g==,type:str]
    DB_USER: ENC[AES256_GCM,data:aO2MedI=,iv:/bBw3ufZLuIlDWqkzQPcrncpl1BSs2L9cosvCzgUmyA=,tag:mbmM14k5c8fxaj2OY/R//w==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:RfNcB8+z32KHYmXlm39yQ03zUN1MErFP8RHSqkkFYC/ZfYbMxUIZQtaBkUs5bSc=,iv:4fSVHzqUk1oPUeQGY6WTGnGUgqdsOohlc2VOCgmQ3s4=,tag:bS6lI4tmVXG8GL90Dc03mQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRDZrbDUzdktteXRKaUtB
            MEpDZjNUTDVIcE1OeWI1YmVlbDBqMmxHZ3pzClRhemhIeHpKbVVQRWg2MUd2QXRn
            WlZwL0NrQ0x6WGxOTzRUR29CR1F2clEKLS0tIFRnM2pjSjJwSzJmdDgzdVFiZTFS
            dFpqVkxFODhsb2F1SWxuVlpvcHJEYjgK/0BwIiyy6CPN9alMtZlYpUBTV67OCR34
            6Ydl9Fa8Z7K4TR8t/YMxtoaIn5XPbx0dZHAScTwHkBA8VKk/EWNe9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-25T09:12:39Z"
    mac: ENC[AES256_GCM,data:oxgRzNVEUJ8G8onpW2WnpRxD7mx8Ui1dceJwr3N34kuzcxJMJGKgoTo4Dm7rHpqMiiZYi1aUC84PAKw/UC5SRLnMn+HOxJcrLJiWHGMTR/3y/24br74IVmdsBFG6fZw1dF14mKiVSsDTquAFUZYypTKt6Tb+58rNVhY7v5ZqhSI=,iv:QOGLO8yybTNMRsTqUcd5Kom3BKbXLhgAiZXk+gv9k/s=,tag:tqrAHm3C/E4fg4xXVFAgRw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
