---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-gateway
spec:
  interval: 30m
  chart:
    spec:
      chart: k8s-gateway
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-gateway
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: k8s-gateway
    domain: "${SECRET_DOMAIN}"
    ttl: 1
    service:
      type: LoadBalancer
      port: 53
      annotations:
        io.cilium/lb-ipam-ips: "192.168.1.192"
      externalTrafficPolicy: Cluster
    watchedResources: ["Ingress", "Service"]
    replicaCount: 3
    fallthrough:
      enabled: true
    extraZonePlugins:
      - name: forward
        parameters: . tls://1.1.1.1 tls://1.0.0.1
        configBlock: |-
          tls_servername cloudflare-dns.com
      - name: log
      - name: errors
      # Serves a /health endpoint on :8080, required for livenessProbe
      - name: health
        configBlock: |-
          lameduck 5s
      # Serves a /ready endpoint on :8181, required for readinessProbe
      - name: ready
      - name: loop
      - name: reload
      - name: loadbalance
