---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
value: 1000000
globalDefault: false
description: "This priority class should be used for XYZ service pods only."

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teslamate-solar-f
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 30
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 30
  uninstall:
    keepHistory: false
  values:
    image:
      repository: pkuehnel/teslasolarcharger
      tag: 2.30.0@sha256:cddd48c05b8dcbf6b8adc4f65fdd651dcd3abf6ad35bb050c996f354e06a91e6
    env:
      TZ: "Europe/Paris"
      DISABLE_MQTT: "false"
#      BleBaseUrl: "http://192.168.1.123:7210/api"
    envFrom:
      - secretRef:
          name: teslamate-secret
    service:
      main:
        type: ClusterIP
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        annotations:
          hajimari.io/icon: mdi:car
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          authentik.domain-auth.home.arpa/enabled: "true"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Tesla Solar F"
          gethomepage.dev/description: "Gestion recharge solaire Tesla"
          gethomepage.dev/group: Surveillance
          gethomepage.dev/icon: "teslamate.png"
        ingressClassName: "external"
        hosts:
          - host: "teslamate-solar-f.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - "teslamate-solar-f.${SECRET_DOMAIN}"
#    tolerations:
#      - key: "arm"
#        operator: "Exists"
    resources:
      requests:
        memory: 250Mi
        cpu: 50m
      limits:
        memory: 500Mi
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    persistence:
      teslasolarcharger-configs:
        enabled: true
        mountPath: /app/configs/
        size: 1Gi
        storageClass: ceph-block
        accessMode: ReadWriteOnce

    priorityClassName: "high-priority"
