---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coredns
spec:
  interval: 30m
  chart:
    spec:
      chart: coredns
      version: 1.34.0
      sourceRef:
        kind: HelmRepository
        name: coredns
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: coredns
    replicaCount: 3
    # In this mode CoreDNS is deployed as any kubernetes app in user specified namespace.
    # The CoreDNS service can be exposed outside the cluster by using using either the NodePort or LoadBalancer type of service.
    # This mode is chosen by setting isClusterService to false
    isClusterService: false
    serviceType: LoadBalancer
    service:
      name: kube-dns
      annotations:
        io.cilium/lb-ipam-ips: 192.168.1.212
      externalTrafficPolicy: Cluster
      clusterIP: 10.96.0.10
    serviceAccount:
      create: true
    deployment:
      annotations:
        reloader.stakater.com/auto: "true"
    servers:
      - zones:
          - zone: .
            scheme: dns://
            use_tcp: true
        port: 53
        plugins:
          - name: log
          - name: errors
          - name: health
            configBlock: |-
              lameduck 5s
          - name: ready
          - name: kubernetes
            parameters: cluster.local in-addr.arpa ip6.arpa
            configBlock: |-
              pods insecure
              fallthrough in-addr.arpa ip6.arpa
              ttl 30
          - name: prometheus
            parameters: 0.0.0.0:9153
          - name: forward
            parameters: . /etc/resolv.conf
          - name: cache
            parameters: 30
          - name: loop
          - name: reload
          - name: loadbalance
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists
    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: coredns
