---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app jdownloader
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: docker.io/jlesage/jdownloader-2
              tag: v24.09.1
            env:
              TZ: Europe/Paris
              MYJDOWNLOADER_DEVICE_NAME: "Kube"
#              # General Settings
#              KEEP_APP_RUNNING: false
#              # GUI Settings
#              DISPLAY_WIDTH: 1280
#              DISPLAY_HEIGHT: 768
#              SECURE_CONNECTION: false
#              ENABLE_CJK_FONT: false
#              CONTAINER_DEBUG: true
#              LANG: es_MX.UTF-8
            envFrom:
              - secretRef:
                  name: jdownloader-jdownloader2-secret

#            nodeSelector:
#              kubernetes/.io/hostname: "node-3"

            securityContext:
              readOnlyRootFilesystem: false
              runAsNonRoot: false

            podSecurityContext:
              runAsUser: 0
              runAsGroup: 0
              fsGroup: 568
              fsGroupChangePolicy: OnRootMismatch

            resources:
              requests:
                cpu: 100m
                memory: 100Mi
              limits:
                memory: 500Mi
    service:
      main:
        ports:
          http:
            port: 5800
    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          authentik.domain-auth.home.arpa/enabled: "true"

          hajimari.io/icon: mdi:download-box
          hajimari.io/enable: "true"
          hajimari.io/appName: "JD2"

          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "JDownloader2"
          gethomepage.dev/description: ""
          gethomepage.dev/group: Média
          gethomepage.dev/icon: "jdownloader.png"
        hosts:
          - host: &host jd2.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        mountPath: /config
        size: 1Gi
        storageClass: ceph-block
        accessMode: ReadWriteOnce
      output:
        enabled: true
        type: nfs
        server: "192.168.1.101"
        path: /mnt/Entertainments/Downloads
        mountPath: /output
        readOnly: false
