apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grocy-restic-secret
  namespace: default
spec:
  target:
    name: grocy-restic-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        RESTIC_REPOSITORY: |-
          {{ .restic_url }}/grocy
        RESTIC_PASSWORD: |-
          {{ .restic_password }}
        AWS_ACCESS_KEY_ID: |-
          {{ .aws_key_id }}
        AWS_SECRET_ACCESS_KEY: |-
          {{ .aws_secret_access_key }}
  data:
    - secretKey: restic_url
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 95b1ea75-dcab-4233-be2f-b0aa00c42f8e
        property: restic_url
    - secretKey: restic_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 95b1ea75-dcab-4233-be2f-b0aa00c42f8e
        property: restic_password
    - secretKey: aws_key_id
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: cf22cba5-8c5f-4fa6-afbc-b0aa00c4786e
        property: aws_key_id
    - secretKey: aws_secret_access_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: cf22cba5-8c5f-4fa6-afbc-b0aa00c4786e
        property: aws_secret_access_key
