---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./tesla-dashcam.yaml
labels:
  - pairs:
      app.kubernetes.io/name: tesla-dashcam
      app.kubernetes.io/instance: tesla-dashcam
