---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-config
spec:
  storageClassName: nextcloud-config
  capacity:
    storage: 1Mi # Size does not matter
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.101
    path: /mnt/Backup/nextcloud/config
  # Note: The first two options are strictly for NFSv4.2
  mountOptions: ["nfsvers=4.2", "nconnect=8", "hard"]

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-config
  namespace: default
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: nextcloud-config
  resources:
    requests:
      storage: 1Mi # Size does not matter

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data
spec:
  storageClassName: nextcloud-data
  capacity:
    storage: 1Mi # Size does not matter
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.101
    path: /mnt/Backup/nextcloud/data
  # Note: The first two options are strictly for NFSv4.2
  mountOptions: ["nfsvers=4.2", "nconnect=8", "hard"]

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: default
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: nextcloud-data
  resources:
    requests:
      storage: 1Mi # Size does not matter
