---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-registry-ui
  namespace: flux-system
#  labels:
#    substitution.flux.home.arpa/enabled: 'true'
spec:
  dependsOn:
    - name: cluster-apps-rook-ceph-cluster
    - name: cluster-apps-volsync
    - name: cluster-apps-nginx-external
    - name: cluster-apps-registry
  path: './kubernetes/apps/default/registry-ui/app/'
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: registry-ui
      namespace: default
  interval: 30m
  retryInterval: 1m
  timeout: 3m
