---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-epic-free-games
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-nginx-external
    - name: cluster-apps-rook-ceph-cluster
    - name: cluster-apps-volsync
  interval: 10m
  path: "./kubernetes/apps/other/epic-free-games/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
