---
apiVersion: v1
kind: Secret
metadata:
  name: emqx-restic-secret
  namespace: default
type: Opaque
stringData:
  RESTIC_REPOSITORY: "${S3_RESTIC_URL}/emqx"
  RESTIC_PASSWORD: "${RESTIC_PASSWORD}"
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"

---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: emqx
  namespace: default
spec:
  sourcePVC: emqx-data-emqx-0
  trigger:
    schedule: "0 22 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 10
    repository: emqx-restic-secret
    cacheCapacity: 2Gi
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    #https://volsync.readthedocs.io/en/stable/design/restic.html
    retain:
      hourly: 24
      daily: 30
      weekly: 52
      monthly: 12
      yearly: 10
