---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-abrp
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: 'true'
spec:
  dependsOn:
    - name: cluster-apps-teslamate

  path: './kubernetes/apps/default/abrp/app/'
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: abrp
      namespace: default
---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-abrp-model-y
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: 'true'
spec:
  dependsOn:
    - name: cluster-apps-teslamate
  path: './kubernetes/apps/default/abrp/app-model-y/'
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: abrp-model-y
      namespace: default
