apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-chris-secret
    namespace: home-automation
type: Opaque
stringData:
    HASS_POSTGRES_URL: ENC[AES256_GCM,data:LISyB/u8g9lsPvYBwU6vQjCu6dKrRdCOEK9zW/JPphZqgvXXmVr6vUi3bcQnrIuOuLhckgv1W40ysyL7ENGz27ETrMUtSo2ENSf8VF1cMQIlX5CcvN1DRJvs,iv:lIhFprie8x+DMXnciiQfYYxE+1A/hybqFor8JCBWz6Q=,tag:kkWltWzmMAny9Lv/qMuO1g==,type:str]
    #ENC[AES256_GCM,data:aOAYXdIMYaAoGXrBxK8=,iv:d7cSQLG2LXQ3MbXwKRNsnM5VJSE0sIFQnMFV+BfGfmI=,tag:m0NMqtHBi5xJzR4D6Zy4/Q==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:4kf79m6w4PQ9vJU9lO250/wD5Iw=,iv:IDca2vtON2CiLeJJxtZ5Lz9wz/Dr8ukcPrDX5pRlrMI=,tag:kNLmmgi+Y2tqsVYkvLqAdQ==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:5ZkcztKxcvnhFEuE8dYWaLcr5NzpNfUrFg4UD/i5wspgI0l4WBp5dJL5,iv:qMWAYu8G9APgLtM3M6kzZzDjfdN/W2qMkilzCUdC+jg=,tag:MHBcKjVyj5YP9CzTRYz9gQ==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:JOUb8w12Wg==,iv:ThjrX/faUxyAZ1CbKkA7A/6L1R01V1GhsnnulfF4DJU=,tag:NzVbnrZtqsPvJMOZSuv7uQ==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:KBwIfT0nsQ==,iv:fTYxXCbkNwRnoSzpVcbpQgyJLfUoOsiDwOu3wQ0YDWA=,tag:UhGxJy80z61lFkeCEpnBKA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:74gQOHk=,iv:Eovp5dRE9pLFa//NFbnXZKYdGdltN7rdvm1srBehq4M=,tag:oa799M9fXJhLnYP8yOhkLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYWxrd21MM1BVRm5vU3pn
            VDBlSnVqdHJGYjU4UFEzTFFnL2IwaEpKd21nCjlRMmg4b0tkaC9iamE4endHZlM1
            RTRRMWVoaFVTb1p6cFFPRUQ2eWFvTkUKLS0tIGEvbHdSb0V0MjRzdWQ0NlRQT1p3
            UVpRQkFSWW1FTFlRdTMreUZHd0FuQjgKNcgKDrqr/1UVWn+JJ7FZuV9ussEmBM3X
            +uDGv2g4HuIE6eNEEp7oJ3gyIs7z0QfihGBvqu+85F6hbeHj3k5pCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-16T04:26:33Z"
    mac: ENC[AES256_GCM,data:FsBiU50vuBWfaFP02Xdt0IhVrf1FKLhfLRYGeGi3sQt6Vg0hpbR7ikGbnpQVZYDs17KUJ7O5UJ5YpihsmyfO0YV2zHKwVTmpSFh7PvT/y3vuQ0rHwLDDcqtC6hhbmO8/NFskkzhfDwpir1TzrTmRK2x6zxriCNgb11ltvqNOvfE=,iv:fivYSYFgBUjcBOjRQXLrVfcHSSYh4vUnkh1CfnZPnXU=,tag:1ojJa65Y1PDWnBqVfm80jw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
