---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./helmrelease.yaml
#  - ./volsync.yaml
labels:
  - pairs:
      app.kubernetes.io/name: teslamate-api
      app.kubernetes.io/instance: teslamate-api
