apiVersion: v1
kind: Secret
metadata:
    name: teslamate-api-secret
    namespace: default
type: Opaque
stringData:
    API_TOKEN: ENC[AES256_GCM,data:vtFDle4TXKkt7jYrINEAkJ8Dw0swoynUCUSFKXn4okXPJ1JkTUJCOMbBiOngrAnRj1QRU9CkXb6nZpucZWzbcXQ3WtANODHhduuK38rdwzj1+RbNyEO3VCr3vyVOrI9rqYkzpbfw05nmxTJxXV6+dS/sKA6Cgimx077WWhMJ3kQ+P61Nj1M7/hm/pNC6FeOAM8QGynJ6I2YYCPYUlHeTwyNLieXeOiJC6yWN/X31IlSmx8F8Hv005lCTVLr9jmPXu9PCDzk7LmDEDgw6c+7o5WhgQAE=,iv:tWZX8XM1NIl2xoU9S38LoxQXt0aKbrVvIGrZzYtWVns=,tag:vjxxmEdDuYPF28DjL2PoxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZVZMU3pvZjVmalNqM2tX
            dWRvWXZyWHhZb2RMaUJjRWVrVUt0ZWZPdlU0ClRiSUZlWE85QXV1ejFia3l1R1NF
            SjZCblpxMkorZlFDTmJaaVVrUjlTZncKLS0tIDczVGtlZTA0M3BMeDFNYk9td1pu
            VUc5UndRNHJldDFSUmRnSkIwNmh2MFUKisznod3Gz7jmt21tcf7LlB3kAijb3V2s
            QP2q/cI7cpDsZBCbtmSURKqjA1NSMaWZ75Z+TytaUtDLiIufiuuFMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-24T06:47:49Z"
    mac: ENC[AES256_GCM,data:3PBwhozlYvuGRrf0MmnEDJLckzkPRbBi7EdXlPhvcEKE+noeTp57p20HmEZmkjU/mPJA96euPLixY41071LDopdhUTGevDGj6zs5g4ltnME6Qr4ww+E5+19Nzjc70xav9mnFMWikhXdh/4AsLLo0XZLiK++Jw1qw22O/X4XQqNM=,iv:c6do/40F88TSrcB3WaHvYMHqinjXwtj0ZzgvPQ+30mE=,tag:l+eD3KIVp3qiJB6Uwm+LMQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
