apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-data
  namespace: security
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  storageClassName: ceph-block
