apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: default
type: Opaque
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:2dOI+Nua6xPUiyhCWPhJYw==,iv:nUu04PuDSaGdqtnpg5pe7KWLFDw49TgxjGEIfXdsCLw=,tag:4gbHlpppABHsYlZ9Xts7Og==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:lLY1v9OY2Ap7pAZBS0XYF3ktxUJ0LvFwAElvXhvYd9WWpKEoBDPFIQ==,iv:bsbwfjqwKeJviBHQBNLd+YZBVW/xF8r7kzwqxKWb32c=,tag:NZgKh+TK+ydpoS0UaTuixg==,type:str]
    MINIO_PROMETHEUS_TOKEN: ENC[AES256_GCM,data:yF7WAg7aQdl1Jzd/DxeDevUs4jeD+Gd+5F/KqwD51Ba6jYY0A9eXKf49aaYE//7I9Gs=,iv:5MOhXLbAZR5UAU6lDBCO5h28xleCLRwNKv68rig71g4=,tag:GzZoQVqcq+5mjDaogcqnPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlaS9IVDdUMmo0OGVYcTZN
            SkllOTFOSEVuL3diZEJ6dm4rL0dpQnpvSFE0CnZscFdrV21TZmdjTzJkVGh3dzJ1
            Z0Q5bFc0VzRyRlh6YmtHUVkvUTZzQTgKLS0tIDBPNFBoaEtHbjNJZXhMZUl3Tkxo
            U1BOU3dvTStKK0FoUUlFdHV5SWNxeDAKD0jK1vtljPj06QHsCKNQdHhR3eCrXTUx
            R3ZJGJet7bkdFuo0ANtoqPio6WCL06SVt4kfe26W9nObYEnZqRDDNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-16T04:26:33Z"
    mac: ENC[AES256_GCM,data:5Pt+qVU9Qn0nivboR8tR73f2HWQj9aKT67XCgvMox/XbQvPnUD247jBb2C6ZBuCytWh+gvTx8pdp9gUUsgTt7qXWSJD52iscJSU3QP3F7/eP2vhuVW4zA0uaP7aDY3/bPKgJrdSyLf9dU8dSt2UxVcLGfVexD2cCufZWqiPjJuc=,iv:wig4cI2At9Wtd6P4DhCDZPNoAhLzgQkh1orBrSIL/1A=,tag:WlncCwFeJaB2/IRVXP8sdQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
