---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grafana
  namespace: observability
spec:
  interval: 15m
  chart:
    spec:
      chart: grafana
      version: 7.3.0
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 30
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 30
  uninstall:
    keepHistory: false
  values:
    deploymentStrategy:
      type: Recreate
#    extraInitContainers:
#      - name: init-db
#        image: ghcr.io/onedr0p/postgres-initdb:14.8
#        imagePullPolicy: IfNotPresent
#        envFrom:
#          - secretRef:
#              name: grafana-secret
    replicas: 1
    rbac:
      pspEnabled: false
    testFramework:
      enabled: false
    # admin:
    #   existingSecret: grafana-secret
    env:
      GF_ANALYTICS_CHECK_FOR_UPDATES: false
      GF_AUTH_GENERIC_OAUTH_API_URL: "https://auth.${SECRET_DOMAIN}/api/oidc/userinfo"
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://auth.${SECRET_DOMAIN}/api/oidc/authorization"
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: grafana
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://auth.${SECRET_DOMAIN}/api/oidc/token"
      GF_DATE_FORMATS_USE_BROWSER_LOCALE: true
      GF_EXPLORE_ENABLED: true
      GF_GRAFANA_NET_URL: https://grafana.net
      GF_LOG_FILTERS: rendering:debug
      GF_LOG_MODE: console
      GF_PANELS_DISABLE_SANITIZE_HTML: true
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: natel-discrete-panel,pr0ps-trackmap-panel,panodata-map-panel,natel-plotly-panel,alexandra-trackmap-panel
      GF_SECURITY_ALLOW_EMBEDDING: true
      GF_SECURITY_COOKIE_SAMESITE: grafana
      GF_SERVER_ROOT_URL: "https://grafana.${SECRET_DOMAIN}/"
      GF_SERVER_SERVE_FROM_SUB_PATH: false
      GF_DASHBOARDS_MIN_REFRESH_INTERVAL: 10ms

    envFromSecrets:
      - name: grafana-secret
    grafana.ini:
      analytics:
        check_for_updates: false
        check_for_plugin_updates: false
      auth:
        signout_redirect_url: "https://auth.${SECRET_DOMAIN}/logout"
        oauth_auto_login: true
      auth.generic_oauth:
        enabled: true
        name: Authelia
        client_id: # Set by env vars
#        client_secret: # Set by env vars secret
        auth_url: # Set by env vars
        token_url: # Set by env vars
        api_url: # Set by env vars
        scopes: "openid profile email groups"
        empty_scopes: false
        login_attribute_path: preferred_username
        groups_attribute_path: groups
        name_attribute_path: name
        use_pkce: true
      auth.generic_oauth.group_mapping:
        role_attribute_path: |
          contains(groups[*], 'admins') && 'Admin' || contains(groups[*], 'people') && 'Viewer'
        org_id: 1
      auth.basic:
        enabled: true
        disable_login_form: false
      auth.anonymous:
        enabled: true
        org_name: HomeOps
        org_id: 1
        org_role: Viewer
      date_formats:
        use_browser_locale: true
      explore:
        enabled: true
      grafana_net:
        url: https://grafana.net
      log:
        mode: console
      news:
        news_feed_enabled: false
      panels:
        disable_sanitize_html: true
      paths:
        data: /var/lib/grafana/data
        logs: /var/log/grafana
        plugins: /var/lib/grafana/plugins
        provisioning: /etc/grafana/provisioning
      security:
        allow_embedding: true
        cookie_samesite: grafana
      server:
        root_url: "https://grafana.${SECRET_DOMAIN}/"

    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: "default"
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
          - name: 'teslamate'
            orgId: 1
            folder: TeslaMate
            folderUid: Nr4ofiDZk
            type: file
            disableDeletion: false
            editable: true
            updateIntervalSeconds: 86400
            options:
              path: /var/lib/grafana/dashboards/teslamate/dashboards
          - name: 'teslamate-internal'
            orgId: 1
            folder: TeslaMateInternal
            folderUid: Nr5ofiDZk
            type: file
            disableDeletion: false
            editable: true
            updateIntervalSeconds: 86400
            options:
              path: /var/lib/grafana/dashboards/teslamate/dashboards_internal
          - name: 'teslamate-reports'
            orgId: 1
            folder: TeslaMateReports
            folderUid: Nr6ofiDZk
            type: file
            disableDeletion: false
            editable: true
            updateIntervalSeconds: 86400
            options:
              path: /var/lib/grafana/dashboards/teslamate/dashboards_reports
    datasources:
      datasources.yaml:
        apiVersion: 1
        deleteDatasources:
          - name: Loki
            orgId: 1
          - name: Alertmanager
            orgId: 1
        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            url: http://thanos-query-frontend.observability.svc.cluster.local:9090
            # url: http://thanos-query-frontend.observability.svc.cluster.local:10902
            isDefault: true
          - name: Loki
            type: loki
            access: proxy
            url: http://loki-gateway.observability.svc.cluster.local
            jsonData:
              maxLines: 250
          - name: Alertmanager
            type: alertmanager
            access: proxy
            url: http://kube-prometheus-stack-alertmanager.observability.svc.cluster.local:9093
            jsonData:
              implementation: prometheus
          - name: TeslaMate
            type: postgres
            url: "postgres-v15-r.database.svc.cluster.local"
            user: "${SECRET_USERNAME}"
            secureJsonData:
              password: "${SECRET_PASSWORD}"
            jsonData:
              sslmode: "disable"
              database: "teslamate"
              postgresVersion: '15'
          - name: HomeAssistant
            type: postgres
            url: "postgres-v15-r.database.svc.cluster.local"
            user: "${SECRET_USERNAME}"
            secureJsonData:
              password: "${SECRET_PASSWORD}"
            jsonData:
              sslmode: "disable"
              database: "home_assistant"
              postgresVersion: '15'
          - name: MyElectricalData
            type: postgres
            url: "postgres-v15-r.database.svc.cluster.local"
            user: "${SECRET_USERNAME}"
            secureJsonData:
              password: "${SECRET_PASSWORD}"
            jsonData:
              sslmode: "disable"
              database: "myelectricaldata"
              postgresVersion: '15'
          - name: InfluxDB-MyElectricalData
            type: influxdb
            access: proxy
            url: http://influxdb-influxdb2.observability.svc.cluster.local:80
            jsonData:
              version: Flux
              organization: influxdata
              defaultBucket: myelectricaldata
              tlsSkipVerify: true
            secureJsonData:
              token: ${INFLUXDB_SECRET}

    dashboards:
      teslamate-internal:
        teslamate-internal-charge-details:
          url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/internal/charge-details.json
          datasource: TeslaMate

        teslamate-internal-drive-details:
          url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/internal/drive-details.json
          datasource: TeslaMate

      teslamate:
        carloscuezva-teslamate-battery-health:
          url: https://raw.githubusercontent.com/CarlosCuezva/dashboards-Grafana-Teslamate/main/dashboards/battery-health.json
          datasource: TeslaMate
        carloscuezva-teslamate-charges:
          url: https://raw.githubusercontent.com/CarlosCuezva/dashboards-Grafana-Teslamate/main/dashboards/charges.json
          datasource: TeslaMate
        carloscuezva-teslamate-charging-costs-stats:
          url: https://raw.githubusercontent.com/CarlosCuezva/dashboards-Grafana-Teslamate/main/dashboards/charging-costs-stats.json
          datasource: TeslaMate
          folder:
        carloscuezva-teslamate-charging-curves:
          url: https://raw.githubusercontent.com/CarlosCuezva/dashboards-Grafana-Teslamate/main/dashboards/charging-curves.json
          datasource: TeslaMate
        carloscuezva-teslamate-charging-tops:
          url: https://raw.githubusercontent.com/CarlosCuezva/dashboards-Grafana-Teslamate/main/dashboards/charging-tops.json
          datasource: TeslaMate
          folder:
        carloscuezva-teslamate-current-charge-view:
          url: https://raw.githubusercontent.com/CarlosCuezva/dashboards-Grafana-Teslamate/main/dashboards/current-charge-view.json
          datasource: TeslaMate
        carloscuezva-teslamate-drive-tops:
          url: https://raw.githubusercontent.com/CarlosCuezva/dashboards-Grafana-Teslamate/main/dashboards/drive-tops.json
          datasource: TeslaMate
          folder:
        carloscuezva-teslamate-drives:
          url: https://raw.githubusercontent.com/CarlosCuezva/dashboards-Grafana-Teslamate/main/dashboards/drives.json
          datasource: TeslaMate
        carloscuezva-teslamate-locations:
          url: https://raw.githubusercontent.com/CarlosCuezva/dashboards-Grafana-Teslamate/main/dashboards/locations.json
          datasource: TeslaMate
        carloscuezva-teslamate-overview:
          url: https://raw.githubusercontent.com/CarlosCuezva/dashboards-Grafana-Teslamate/main/dashboards/overview.json
          datasource: TeslaMate
        carloscuezva-teslamate-states:
          url: https://raw.githubusercontent.com/CarlosCuezva/dashboards-Grafana-Teslamate/main/dashboards/states.json
          datasource: TeslaMate
        carloscuezva-teslamate-tire-pressure:
          url: https://raw.githubusercontent.com/CarlosCuezva/dashboards-Grafana-Teslamate/main/dashboards/tire-pressure.json
          datasource: TeslaMate

        jheredianet-teslamate-continuous-trip:
          url: https://raw.githubusercontent.com/jheredianet/Teslamate-CustomGrafanaDashboards/main/dashboards/ContinuousTrips.json
          datasource: TeslaMate

        teslamate-battery-health-lfp:
          url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/battery-health-lfp.json
          datasource: TeslaMate
        teslamate-charge-level:
          url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/charge-level.json
          datasource: TeslaMate
        teslamate-charging-stats:
          url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/charging-stats.json
          datasource: TeslaMate
        teslamate-charging-stats-lfp:
          url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/charging-stats-lfp.json
          datasource: TeslaMate
        teslamate-drive-stats:
          url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/drive-stats.json
          datasource: TeslaMate
        teslamate-drives:
          url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/drives.json
          datasource: TeslaMate
        teslamate-efficiency:
          url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/efficiency.json
          datasource: TeslaMate
        teslamate-locations:
          url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/locations.json
          datasource: TeslaMate
        teslamate-mileage:
          url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/mileage.json
          datasource: TeslaMate
        teslamate-overview:
          url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/overview.json
          datasource: TeslaMate
        teslamate-overview-lfp:
          url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/overview-lfp.json
          datasource: TeslaMate
        teslamate-projected-range:
          url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/projected-range.json
          datasource: TeslaMate
        teslamate-states:
          url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/states.json
          datasource: TeslaMate
        teslamate-statistics:
          url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/statistics.json
          datasource: TeslaMate
        teslamate-timeline:
          url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/timeline.json
          datasource: TeslaMate
        teslamate-trip:
          url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/trip.json
          datasource: TeslaMate
        teslamate-updates:
          url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/updates.json
          datasource: TeslaMate
        teslamate-vampire-drain:
          url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/vampire-drain.json
          datasource: TeslaMate
        teslamate-visited:
          url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/visited.json
          datasource: TeslaMate

      default:
        # Ref: https://grafana.com/grafana/dashboards/11312-unifi-poller-usw-insights-prometheus/
        unifi-usw:
          gnetId: 11312
          revision: 9
          datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/7845-zfs/
        zfs:
          gnetId: 7845
          revision: 4
          datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/13502-minio-dashboard/
        minio:
          gnetId: 13502
          revision: 21
          datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/1860-node-exporter-full/
        node-exporter-full:
          gnetId: 1860
          revision: 30
          datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/763-redis-dashboard-for-prometheus-redis-exporter-1-x/
        redis:
          gnetId: 763
          revision: 4
          datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/5342-ceph-pools/
        ceph-pools:
          gnetId: 5342
          revision: 9
          datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/5336-ceph-osd-single/
        ceph-osd:
          gnetId: 5336
          revision: 9
          datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/2842-ceph-cluster/
        ceph-cluster:
          gnetId: 2842
          revision: 16
          datasource: Prometheus
        cert-manager:
          url: https://raw.githubusercontent.com/observability-mixins/website/master/assets/cert-manager/dashboards/cert-manager.json
          datasource: Prometheus
        external-secrets:
          url: https://raw.githubusercontent.com/external-secrets/external-secrets/main/docs/snippets/dashboard.json
          datasource: Prometheus
        flux-cluster:
          url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/observability/observability-config/dashboards/cluster.json
          datasource: Prometheus
        flux-control-plane:
          url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/observability/observability-config/dashboards/control-plane.json
          datasource: Prometheus
        flux-logs:
          url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/observability/observability-config/dashboards/logs.json
          datasource: Prometheus
        kubernetes-api-server:
          url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
          datasource: Prometheus
        kubernetes-coredns:
          url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-coredns.json
          datasource: Prometheus
        kubernetes-global:
          url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
          datasource: Prometheus
        kubernetes-namespaces:
          url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json
          datasource: Prometheus
        kubernetes-nodes:
          url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
          datasource: Prometheus
        kubernetes-pods:
          url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
          datasource: Prometheus
    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL
        # folderAnnotation: grafana_folder
        # provider:
        #   foldersFromFilesStructure: true
      datasources:
        enabled: true
        searchNamespace: ALL
      logLevel: INFO
    plugins:
      - grafana-clock-panel
      - grafana-piechart-panel
      - grafana-worldmap-panel
      - natel-discrete-panel
      - pr0ps-trackmap-panel
      - vonage-status-panel
      - alexandra-trackmap-panel
#      - panodata-map-panel
#      - natel-plotly-panel
    serviceMonitor:
      enabled: true
    ingress:
      enabled: true
      ingressClassName: external
      annotations:
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hajimari.io/icon: simple-icons:grafana
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Grafana"
        gethomepage.dev/description: "Graph détaillés"
        gethomepage.dev/group: Surveillance
        gethomepage.dev/icon: "grafana.png"

      hosts:
        - &host "grafana.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - *host
    imageRenderer:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - node-3
                      - worker-1

      enabled: true
      replicas: 1
      networkPolicy:
        limitIngress: false
      serviceMonitor:
        enabled: true
    persistence:
      enabled: true
      storageClassName: ceph-block
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - node-3
                    - worker-1

#    topologySpreadConstraints:
#      - maxSkew: 1
#        topologyKey: kubernetes.io/hostname
#        whenUnsatisfiable: DoNotSchedule
#        labelSelector:
#          matchLabels:
#            app.kubernetes.io/name: grafana
