apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: esphome-externalsecret
  namespace: home-automation
spec:
  target:
    name: esphome-secret
    deletionPolicy: Delete
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        secrets.yaml: |-
          wifi_ssid: "{{ .wifi_ssid }}"
          wifi_password: "{{ .wifi_password }}"

          ota_password: "{{ .ota_password }}"
  data:
    - secretKey: wifi_ssid
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 5ffe4656-a11b-4df1-8670-b0d4009dc635
        property: wifi_ssid
    - secretKey: wifi_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 5ffe4656-a11b-4df1-8670-b0d4009dc635
        property: wifi_password
    - secretKey: ota_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 5ffe4656-a11b-4df1-8670-b0d4009dc635
        property: ota_password
