---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ecojoko-exporter
  namespace: observability
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 30
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 30
  uninstall:
    keepHistory: false

  values:
    controller:
      replicas: 1
      strategy: RollingUpdate
    image:
      repository: "registry.${SECRET_DOMAIN}/ecojoko-exporter"
      tag: "latest"
    envFrom:
      - secretRef:
          name: ecojoko-secret

    resources:
      requests:
        cpu: 15m
        memory: 64M
      limits:
        memory: 124M

    service:
      main:
        ports:
          http:
            port: 3226

    ingress:
      main:
        enabled: true
        ingressClassName: "internal"
        annotations:
          external-dns.home.arpa/enabled: "true"
          external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/whitelist-source-range: |
            10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
