---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: influxdb
  namespace: observability
spec:
  releaseName: influxdb
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.influxdata.com/
      chart: influxdb2
      version: 2.1.2
      sourceRef:
        kind: HelmRepository
        name: influxdata-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: "influxdb"
      tag: "2.7.10"
    service:
      type: ClusterIP
      port: 80
      targetPort: 8086
      portName: http
    ingress:
      enabled: true
      className: external
      hostname: "influxdb.${SECRET_DOMAIN}"
      annotations:
        #        cert-manager.io/cluster-issuer: self-signed-issuer
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hajimari.io/enable: "true"
        hajimari.io/icon: logos:influxdb
        hajimari.io/info: influxdb
        hajimari.io/group: admin
        nginx.ingress.kubernetes.io/proxy-body-size: "100m"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          auth_request_set $required_groups 'influxdb_dashboard';
      hosts:
        - "influxdb.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - "influxdb.${SECRET_DOMAIN}"

    livenessProbe:
      timeoutSeconds: 10
    readinessProbe:
      timeoutSeconds: 10
    startupProbe:
      enabled: true
      failureThreshold: 10
      periodSeconds: 10
    volumeClaimTemplates:
      - name: influxdb-data
        mountPath: /var/lib/influxdb2
        accessMode: ReadWriteMany
        size: 50i
        storageClass: ceph-block
#
#    persistence:
#      enabled: true
#      useExisting: true
#      name: influxdb-data
#      mountPath: /var/lib/influxdb2
    ## Create default user through docker entrypoint
    ## Defaults indicated below
    ##
    adminUser:
      organization: "influxdata"
      bucket: "home-assistant"
      user: "admin"
      retention_policy: "0s"
      ## Leave empty to generate a random password and token.
      ## Or fill any of these values to use fixed values.
      password: ""
      token: ""
      ## The password and token are obtained from an existing secret. The expected
      ## keys are `admin-password` and `admin-token`.
      ## If set, the password and token values above are ignored.
      # existingSecret: influxdb-auth
