---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app myelectricaldata
  namespace: observability
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 30
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 30
  uninstall:
    keepHistory: false

  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    maxHistory: 2
    image:
      repository: m4dm4rtig4n/myelectricaldata
      tag: latest@sha256:b3278bec23521faf641e0a57578b6a309df114b160aef13d587bca6cd65c80af
    volumeMounts:
      - name: data
        mountPath: /data

    env:
      TZ: Europe/Paris
    service:
      main:
        ports:
          http:
            port: 5000

    ingress:
      main:
        enabled: true
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/appName: "myelectricaldata"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "MyElectricalData"
          gethomepage.dev/description: "Info consommation Enedis"
          gethomepage.dev/group: Surveillance
          gethomepage.dev/icon: "https://myelectricaldata.${SECRET_DOMAIN}/favicon.ico"
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          authentik.domain-auth.home.arpa/enabled: "true"

        ingressClassName: "external"
        hosts:
          - host: &host "myelectricaldata.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

#    volumeClaimTemplates:
#      - name: data
#        mountPath: /data
#        accessMode: ReadWriteOnce
#        size: 1Gi
#        storageClass: ceph-block
    persistence:
      data:
        enabled: true
        storageClass: "ceph-block"
        accessMode: ReadWriteOnce
        size: 1Gi
#
#    nodeSelector:
#      kubernetes.io/hostname: "node-3"
