# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headscale
spec:
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: bjw-s
  interval: 1h
  values:
    controllers:
      headscale:
        containers:
          app:
            image:
              repository: ghcr.io/juanfont/headscale
              tag: 0.22.3@sha256:aadf29a875bb2ffdf6579869e5759935f7a64b9fd19fcea9d5385c5d7220dc7b
            command: [headscale]
            args: [serve]
            probes:
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
              liveness:
                enabled: true
              readiness:
                enabled: true
            securityContext:
              readOnlyRootFilesystem: true
      ui:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/gurucomputing/headscale-ui
              tag: 2024.02.24-beta1@sha256:4c618a7b6e8b32f5ef6af3c7e6936c63e8568ad9ae8d190dafb2551a64ff40a2
            securityContext:
              readOnlyRootFilesystem: true
      ui2:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: goodieshq/headscale-admin
              tag: latest
            securityContext:
              readOnlyRootFilesystem: true
            env:
              TZ: Europe/Paris
              HS_SERVER: "https://ts.${SECRET_DOMAIN}"
              BASE_PATH: /admin
            envFrom:
              - secretRef:
                  name: headscale-secret

    defaultPodOptions:
      securityContext:
        sysctls:
          - name: net.ipv4.ip_unprivileged_port_start
            value: '0'
    service:
      headscale:
        controller: headscale
        ports:
          http:
            primary: true
            port: 8080
          metrics:
            port: 9090
      ui:
        controller: ui
        ports:
          http:
            port: 80

      ui2:
        controller: ui2
        ports:
          http:
            port: 80

    persistence:
      config:
        type: secret
        name: headscale-config
        advancedMounts:
          headscale:
            app:
              - path: /etc/headscale/config.yaml
                subPath: config.yaml
          ui2:
            app:
              - path: /etc/headscale/config.yaml
                subPath: config.yaml
      var-lib-headscale:
        existingClaim: headscale
        advancedMounts:
          headscale:
            app:
              - path: /var/lib/headscale
      tmp:
        type: emptyDir
        advancedMounts:
          headscale:
            app:
              - path: /var/run/headscale
                subPath: run
          ui:
            app:
              - path: /data
                subPath: data
              - path: /home/appuser/.local
                subPath: .local
          ui2:
            app:
              - path: /tmp
                subPath: .

      configui2:
        existingClaim: headscale-ui2
        advancedMounts:
          ui2:
            app:
              - path: /data
    ingress:
      headscale:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "direct.${SECRET_DOMAIN}"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
        hosts:
          - host: &host "ts.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: headscale
                  port: http
      ui:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "direct.${SECRET_DOMAIN}"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
        hosts:
          - host: *host
            paths:
              - path: /web
                service:
                  identifier: ui
                  port: http
      ui2:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "direct.${SECRET_DOMAIN}"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          nginx.ingress.kubernetes.io/auth-method: GET
          nginx.ingress.kubernetes.io/auth-url: http://authelia.security.svc.cluster.local/api/verify
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.${SECRET_DOMAIN}?rm=$request_method"
          nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
          nginx.ingress.kubernetes.io/auth-snippet: |
            proxy_set_header X-Forwarded-Method $request_method;
        hosts:
          - host: *host
            paths:
              - path: /admin
                service:
                  identifier: ui2
                  port: http

    secrets:
      config:
        stringData:
          config.yaml: |
            server_url: "https://ts.${SECRET_DOMAIN}"
            listen_addr: 0.0.0.0:8080
            metrics_listen_addr: 0.0.0.0:9090
            private_key_path: /var/lib/headscale/private.key
            noise:
              private_key_path: /var/lib/headscale/noise_private.key
            prefixes:
              v6: fd7a:115c:a1e0::/48
              v4: 100.64.0.0/10
            derp:
              server:
                enabled: false
              urls:
                - https://controlplane.tailscale.com/derpmap/default
              auto_update_enabled: true
              update_frequency: 24h
            disable_check_updates: false
            ephemeral_node_inactivity_timeout: 30m
            database:
              type: sqlite
              sqlite:
                path: /var/lib/headscale/db.sqlite
            # TODO: Remove after 0.23.0
            db_type: sqlite3
            db_path: /var/lib/headscale/db.sqlite
            dns_config:
              # Whether to prefer using Headscale provided DNS or use local.
              override_local_dns: true
              # List of DNS servers to expose to clients.
              nameservers:
                - 192.168.1.254
              domains: []
              magic_dns: true
              base_domain: "ts.${SECRET_DOMAIN}"
            log:
              level: debug
