apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: headscale
  namespace: default
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
