---
# yaml-language-server: $schema=https://kubernetes-schemas.thesteamedcrab.com/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: database-phpmyadmin
  namespace: flux-system
spec:
  targetNamespace: database
  path: ./kubernetes/apps/database/phpmyadmin/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
