apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:U/JqKjs5wI5hxiEkOs5pSh5bND0JqAM+qv59vk1pSD7tdOIzt0Z+2Q==,iv:QkdX4OTTy8eAQWnXDWDED2rNQN0kgPFSUplj4B8G/tY=,tag:u9CnqgemM/5EuUi+1js3lA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcGdRQkJ3RjFUS0xMR3NX
            YXN4UEh3TmhLcTVJbGZmODN5ZkRqYWUxRDBvCkt2OFhMTDllc3BDazVoSnRKZDZV
            dUJBWW1aNi9oMjh3dWhsYUhHdXNoVTQKLS0tIERFTEpHeU1HeTUybGtCUDc3ZStu
            WjFkZVY1dkJkYzQ4SGg5cW5JVHAxcFkKUHSPm5EUT7e2thJ/9CO5ACwjbf9+0yl7
            E+vGPsx3dNL/4SmvVTrRLiz3xfc6gEdHqZ/wwzSIBZ68/1V/3S4KCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-13T07:54:20Z"
    mac: ENC[AES256_GCM,data:bfI1j4CSZljiBg50FyqSp5UASY9SoauPv73lzAnUU9PdLpCEPifPp3fZp1O4getTu8A5ozoBZ5Xlrc8EOTY9kS+AaH7kRY082MIw+gk5rd0zu0leGaEg7KfQXf6OB1Jx1T/ZTXBI4oLXY2LG+OUoVOwi602JzSssYXjxwrteS54=,iv:BRPyNwSMIFeAkKFPjj7gvf8mHNbxYoYAtunLiL0ZwK8=,tag:YFO0Em0Nok3Ak1PtaRYsWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
