---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-frigate
  namespace: flux-system
spec:
  path: ./kubernetes/apps/default/frigate/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: cluster-apps-nginx-external
    - name: cluster-apps-rook-ceph-cluster
    - name: cluster-apps-authelia
