---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
resources:
  - ./secret.sops.yaml
  - ./helmrelease.yaml
commonLabels:
  app.kubernetes.io/name: mqtt-exporter
  app.kubernetes.io/instance: mqtt-exporter
