apiVersion: v1
kind: Secret
metadata:
    name: photoprism-secrets
    namespace: default
stringData:
    PHOTOPRISM_ADMIN_USER: ENC[AES256_GCM,data:G0ID3Qo=,iv:kGU7iWxd6DmXktw+cWYJKmIKJHjfJE/ObPWlP5N6IhU=,tag:7xFoanUSpMqrldvqu6TCjQ==,type:str]
    PHOTOPRISM_ADMIN_PASSWORD: ENC[AES256_GCM,data:iAbr7o/aoJwlg+A=,iv:QsGG5urzH1oDjPHoz5Zwl38b1h5z56rKzDDFWOW3fyA=,tag:fvaE7aQZeZEZRVfow/s5HQ==,type:str]
    PHOTOPRISM_DATABASE_SERVER: ENC[AES256_GCM,data:5PrtZeRzbAYvE7Xon7KTIceMsZhPKg5XN3xH9qwgAHopVEtbC/dHvILOJf7JbRQ=,iv:KN+7woYEO4cIuTEK5zzGjA8AoOMat8u2Ym5pNnTad/o=,tag:vQWhDzgwZhbwUakIP1TcQg==,type:str]
    PHOTOPRISM_DATABASE_NAME: ENC[AES256_GCM,data:U5ixXd/yvOQk8A==,iv:QSKn8KUmI+rIPkshzbqCPodhG5xBe0IAzAJY8+jItdY=,tag:qTGx22vL+jlU1eXyk9v8Hw==,type:str]
    PHOTOPRISM_DATABASE_USER: ENC[AES256_GCM,data:WG1Xq38=,iv:sgCVWVD5Nl1bzUaOnT453nuHvPWG3V3DzPh2Qyh/veI=,tag:FFPEr+3gzo65tBHUn/pWtw==,type:str]
    PHOTOPRISM_DATABASE_PASSWORD: ENC[AES256_GCM,data:8KORvNDqVA==,iv:UdMSh33ibGay3e1bytnWFGYHPW6elUu37v375k935Uk=,tag:MtW0NlDlNQFvSH7XEdzumA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURTcvVzA2Nm5DQldDMWZj
            b09tRmwvMDBINGFPS01pcWVqeG9FbnVjZ2drCmJqem5tOFBsN0FiNXE0UmFwY2th
            aE5pRWg5WHJRcVJGUmhCd1VGUHkwSTQKLS0tIGhiOXRQSzlycHFwVnNuVWNZeEgw
            enlEaVZrbkZESjVKWmNrNVFyQURibkUKeb234HISzGdZWc86Fku/faAqH938o6tz
            Jj3TABjJE8l6wrHCelR+oXMopk+LeLvfjhsPVmYn5PZqm7yV3us/oQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-20T12:19:57Z"
    mac: ENC[AES256_GCM,data:dATNcWzdVbsK4qU/x64nyIT4+nPNtotL1nchdLXZY3eKPwrE+3okc/x/k4wq0zR1+oxkCSQcLQbr0/E/uws48m2+pTC+c4xij1Po61rxhAw0kjFaoazPaJpXh9ERbBrifOgjW0Rk8cx9hRBruTU7/Sppj24j5MqvJ83nbVFyVpM=,iv:2GXOHmfyNbW5Lxphz80+jTfuPKFrcR+2b+KLGGoaESs=,tag:VTizpveX0nB32zIvAmmlLA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: photoprism-restic-secret
    namespace: default
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:L9wQlGhwSdW/yxub7UqYxm3iZRA2/fpmdJbd5f7idwHD32XqCndk8VEx,iv:d7i1vB/4KNsibpqkw2A6ZjDzjlISo0Mht93yK/ex5/g=,tag:nAG7a4QNqPS/Tw6qlsi50g==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:v+itDHTT/nQ2RMtcDntJfO0=,iv:7v14R5sXVKyfm4o3jANYN43kyL4phQoVjTiI7XgJQak=,tag:enyNMUZvTCFKqrdrjIbVdQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:C+69S63HyvIiSahnM5Jerw==,iv:+wRWVsG8c2oSPtldBl3F6vPzjtaOtogXu3vSGWAXAyo=,tag:IQcQXhLBElPGJrpbIOIslw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:v3HfgswUMt2n7fxjK3yZ2tfo6m1/mZkYwxPU1JsMDOkMfBRIWeu2uw==,iv:U2EogVHln6buoeK2HPc6GhL5Fq5hLkS3O7+rTPaGmXg=,tag:i0vM8iF9ojv0ZLtQr33gxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURTcvVzA2Nm5DQldDMWZj
            b09tRmwvMDBINGFPS01pcWVqeG9FbnVjZ2drCmJqem5tOFBsN0FiNXE0UmFwY2th
            aE5pRWg5WHJRcVJGUmhCd1VGUHkwSTQKLS0tIGhiOXRQSzlycHFwVnNuVWNZeEgw
            enlEaVZrbkZESjVKWmNrNVFyQURibkUKeb234HISzGdZWc86Fku/faAqH938o6tz
            Jj3TABjJE8l6wrHCelR+oXMopk+LeLvfjhsPVmYn5PZqm7yV3us/oQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-20T12:19:57Z"
    mac: ENC[AES256_GCM,data:dATNcWzdVbsK4qU/x64nyIT4+nPNtotL1nchdLXZY3eKPwrE+3okc/x/k4wq0zR1+oxkCSQcLQbr0/E/uws48m2+pTC+c4xij1Po61rxhAw0kjFaoazPaJpXh9ERbBrifOgjW0Rk8cx9hRBruTU7/Sppj24j5MqvJ83nbVFyVpM=,iv:2GXOHmfyNbW5Lxphz80+jTfuPKFrcR+2b+KLGGoaESs=,tag:VTizpveX0nB32zIvAmmlLA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
