---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: photoprism
  namespace: default
spec:
  sourcePVC: photoprism-config
  trigger:
    schedule: "0 22 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 10
    repository: photoprism-restic-secret
    cacheCapacity: 2Gi
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    #https://volsync.readthedocs.io/en/stable/design/restic.html
    retain:
      hourly: 24
      daily: 30
      weekly: 52
      monthly: 12
      yearly: 10
