---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: esphome-nfs-config
spec:
  storageClassName: esphome-nfs-config
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: "192.168.1.101"
    path: /mnt/Apps/kube/volumes/esphome
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - hard
    - noatime
    - rsize=131072
    - wsize=131072

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esphome-nfs-config
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: esphome-nfs-config
  resources:
    requests:
      storage: 1Mi
