---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.14.3
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    nodeFeatureRule:
      createCRD: true
    master:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - node-3

    worker:
      annotations:
        configmap.reloader.stakater.com/reload: node-feature-discovery-worker-conf
      config:
        core:
          sources:
            - custom
            - pci
            - usb
        sources:
          usb:
            deviceClassWhitelist:
              - "02"
              - "03"
              - "0e"
              - "ef"
              - "fe"
              - "ff"
            deviceLabelFields:
              - class
              - vendor
              - device
#          custom:
#            - name: intel-gpu
#              matchOn:
#                - pciId:
#                    class: ["0300"]
#                    vendor: ["8086"]
