---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-backup-secret
  namespace: database
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
