---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - ./cronjob.yaml
  - ../../cloudnative-pg/app/secret.sops.yaml
commonLabels:
  app.kubernetes.io/name: postgres-backup
  app.kubernetes.io/instance: postgres-backup
