---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN/./-}-production"
spec:
  secretName: "${SECRET_DOMAIN/./-}-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN}"
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "*.${SECRET_DOMAIN}"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${PERSONAL_SECRET_DOMAIN/./-}-production"
spec:
  secretName: "${PERSONAL_SECRET_DOMAIN/./-}-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${PERSONAL_SECRET_DOMAIN}"
  dnsNames:
    - "${PERSONAL_SECRET_DOMAIN}"
    - "*.${PERSONAL_SECRET_DOMAIN}"
