apiVersion: v1
kind: Secret
metadata:
    name: sickchill-restic-secret
    namespace: media
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:l5BaXA1fA/e1qB6PLQ5i1UJq6T55PBEx67k1H4kh4hGi28ghEAevotQ=,iv:WFTykwd2pKLijmff0jP0LXI68N4/e3NU6f7wqBuKPUQ=,tag:mv94ovZ1DKmTBZQTpK744A==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:sTUEe9m+92hanyanP/2QVn8=,iv:uyVJkfMJIgDAzEIbZ9wcZC1rYL9O1fZEobx4GOdNMtE=,tag:z8czkGey71+boMfPsdu3aQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:SV115/IOY+djYPftIxZ/8g==,iv:DGBxAkXv832/Njey6UZFbvLhFIOIWOygh0RipseL4T4=,tag:vFFdInsymJ5AsOeDNBrb3g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:gnINzbpDTMU+csEwjtdt3sv08HG8JjuKKSYV3E+9p8GhIRVCKxqlOA==,iv:M2rJZCfDRPNWXZtgQvZAvfYiQKNOVgOzQC14VJmhOuQ=,tag:CbuivT3cFZcq2cVYTDlT7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvYlVhS3ZKM0JzbFEvQlo1
            MEU2V2tPQitneVFiK04zU0RkMWt1bEdRS3d3CjdUa3Q2aDRhYzJ0Tm5sY3EvU09K
            MFFFaEZRZlNqNGhKcEs2Q2xrNXhuYVEKLS0tIEpWSmt2YUs2eTltN085eDFNRG1w
            QWdwVm50V0JQOXlZbjRYNmRUVjZ1NXcK18dzwTkLFxdMTPpAw+oLgGSrZFoIApT2
            FLHzLPzfUNSDqTyNLDEJI1zgDnE7xNfwdtU2GpTs8tz4+hfumCjx6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-16T04:26:33Z"
    mac: ENC[AES256_GCM,data:qnKq6Mi3K5Ei5sW/pk4GzpU5LcMTbFovZuOFMkTDe30IljOs8tVLe0kRh2vi9kxqDO1uO+jj5mwPIPMGhqcwHhm5RHQohMM8tr3ygIGFCFbDyi2xdexJ96peo8O7Xt9gAm02zsJ3zruedxF2CBDGC1AeQlSbPNvWrnO8IXk3MIg=,iv:eG3kRTOywcSr1ld2PF7uyEjx9G+cKxpMYIbLI2iHvoE=,tag:cLuAKWSSZX+f6nKR1PN8vw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
