apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:XvtAZxg=,iv:2M345X+gq9cH30qVZHWsTjMQhsGwWwBEJeuhGJFQL7M=,tag:/OGb5to6n32o6x83SWdBQw==,type:str]
    password: ENC[AES256_GCM,data:uy+bBs6C/j2uiNBcAZNnSeRCd0Zj7NQh9LNx1AOvVENhYxZYrMYeugWfqEblXRe8KfJgcLJiGexxGM2A,iv:BvGZom6lqOCwYZG3F0y4GOY5t+9oeX8aZUvM8A7R01Q=,tag:Yo9h3lwECP/Jzi5GtJiV0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0cjFuNTlkazBSbDk0TFJL
            b1hYeVlRMzZUWHVCZkRrTzVqSFl4K2d1N1NNCk5KcHFRcyszOW5LSk9JL1ZybTRB
            eUthZ3JldVRvMFFuQ2xjZzBSRy9nNzQKLS0tIGZaM2IyUWpMd0dFVFB0MjJSbEUv
            cXRwOXR2SHc1eWtYSUFvYjlpMGt1M3cKsbpB6xbRTWQK6ctV7YFZViohq7VX1Ag6
            ET3p40OkOqTX8gXnLmSwaa9QGT+OH6/8NzdaaPjepZMYo2751858Yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-16T04:26:33Z"
    mac: ENC[AES256_GCM,data:pR/rXbgnvG3cpmJM8SpVw3JxdA3M3oFvyDSW/HaU4eyhOMtU0eDIWO61saqx60q3AZIyrmx06gE/Enh0rEDGY7DLKobj5d1cs1dM42+sFdI5vbXzO2umkvjl1D4Mx2vuF4YYJKDv0qs6zypF39g96TPYAZZOaTVw2+yvS8Zl1cg=,iv:hsyIgjtqFji1AEMjX7UMYS/YnE5FM4n0hw7/NelPf7U=,tag:h1sG80DDn1Lvf8nrGLy0Pw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
