---
# yaml-language-server: $schema=https://raw.githubusercontent.com/JJGadgets/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: snapshot-controller-validation
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      chart: snapshot-validation-webhook
      version: 1.9.0
      sourceRef:
        kind: HelmRepository
        name: piraeus
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    crds: Skip
    remediation:
      retries: 5
  upgrade:
    crds: Skip
    remediation:
      retries: 5
