apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:+8jL9HrPH44PWS+YNTqf5A==,iv:YlUf4EPv2F9G4ZF1K4cZ4Hp2HjuCRG2u1rGWtyyHHgg=,tag:r403PBfAbZzGx1tMVDTJ5Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:g7/gPQcAf4V3aaN7hZ4Ag0Ihk4wVqfmds7dD355+I3w/BIOf8ry8oA==,iv:UsuWs5urytcjfFtnRM7wkifp13r9TzNeH5/fgJ0Ali8=,tag:ABSsvZM6BDyn9ZCG0E7qXA==,type:str]
    GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:oy58HD3a4tjZFTkB0zsrMZsrD+cv8gW8Y1k9AdKSyJFtxUTMohw15G3wZMegox4XAAAgVaEB8Yx+ZTJQg8ClIhvHaZkbtTSWFUg3QjoIRYyPDXnVqP48ckM=,iv:1PVA95xlK3zeS4q+4j7N/9s8kHvPMYN1KTtcNvNka/o=,tag:Ap1VJDn8F2r3b37bHKBiGg==,type:str]
    HOME_ASSISTANT_PROMETHEUS_TOKEN: ENC[AES256_GCM,data:+YWWWoHwt6Mhqe13d7jZRuIeWArQt9rywdiu13AtZ3x2gUwn12hoXU7v8xO801VQSG3YP0sPHNQQNCamjlOtDSJyeLtNISJ9z67xmfnhZDKj5HJ2hT8mTJaPIcZRmyx888jKtY+4Vh71O0RRTlX8OWgNyhkMtpNEMe2D8uM8pJnXq1xmUYtvX+pzXhtGAhfvp9qalWNzO87rPmwHp9fUN6/Rxw3aRnMc2Xb3DWDBuXC5/NLInkL1,iv:FAcG/4MapDO4y8lvEtl4do0JeK/tKzgMxPVxgqxtbKI=,tag:34gKfC/Op377x8T8e220RA==,type:str]
    INFLUXDB_SECRET: ENC[AES256_GCM,data:MVIRenKexOCot/hHpo4KXbdxmbv2IxLINp0iRNUA+Tpgnxb0I1l/kFHoJ9K4dB4pjyDYgPRWThWAogYVkY0woZqJQAeCP4o3xmBJqn42tmh7C+Fn/SFukQ==,iv:xrDFO7awynwCqt0jvJbqQrWnDBcwmJx8ICKUNbxroks=,tag:EfOfK5bYzeKQJcnCDGPZuA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:+r07jBacwjk7B3M3fhrtSc4=,iv:e5g1SLGLi8Ctrubmasc+bQqWhn9cpbveTSVshgrW3wY=,tag:X49HVSSwyfwIF+LIPToVxg==,type:str]
    S3_RESTIC_URL: ENC[AES256_GCM,data:7R2aGnieTJN9yeQvGjGx0fuXo8/kHHRJ54UVNVwFOw==,iv:ZCF/m6RE/LnOJFNzzv+6S+J1cNjQD163poP/CdYjPmo=,tag:j9G0siNJVRw7A8t/nys1JA==,type:str]
    SECRET_PASSWORD: ENC[AES256_GCM,data:EzRqLYqeQg==,iv:kV/qHtQffEdYKNmdrLc1NeUeabOsIKbudMS0w/xX4oU=,tag:q4HFTZgh/ZG+WS5fT3TsrA==,type:str]
    SECRET_S3_URL: ENC[AES256_GCM,data:9yBFUFRDFE07kF7wqaPkL/gWFArbxByXgqzX,iv:c8IXdLrhNJ/D2qQD6flfKRRtKI4ObXrNPBBRjlE/V9M=,tag:zq7qIed1kZbSaZ0PK8GxEw==,type:str]
    SECRET_USERNAME: ENC[AES256_GCM,data:817+9AM=,iv:y7u/aLa9VioL+iX8YHngssCf62v2SH4nri1Chv1kB1Y=,tag:oBEVMp3wnPuOeIXDqpvNwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TkI0TEgxbk1EOGNjYjQw
            WHBhaUFsUmp2SHZua0FZYlZGaVRhRGxHS0FRCjhLZGpyNko2VDE5NFRwNFlQbUZB
            VTRTYnJYdVdkMWZyUjVvNnNmSVBiQkkKLS0tIDFNaisxZmRWWHZpUlExdnQrOUkr
            djVmT2Uxa2poRHhXemRUSW12cVNHYnMKEx/KNmId3TvTm2Zi0/BEU1VsbpCs+/UN
            UxWTZ+yLHR3nsfCurVu61yvywa+NJO1/sRxDDQ+fB7Mzss+qZP9+IQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-21T09:52:25Z"
    mac: ENC[AES256_GCM,data:yl3jocpBqIrJUVkB/Xed+GyzQLh3eng9SmK4fliIPAiRwMga33tn7rzcYXmv3pSLp50/sQYwyDH8sWc3rJPj2xvdapZgvfxVe2/F9Tu1OmDzUsUillOHf0KnI8yxozMRY5KyUFil1R3mc4Fb8G4mCw99m0BHTLBZ8/tFzFEij9E=,iv:wE8eplNl0LiXOfbQlQzsStnv0BZhm9gFuX3DOYnuKJg=,tag:/8zbrd4Ha9lkkPaUs6I+ww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
