apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:ifZWQs3XGeVwehX0OlY5aJoM7WNP5IGIaGk=,iv:dV18Yc4huPdzcAgAVeSeA2eS3O6EAU5zuA+tV/2yTM8=,tag:dedcrB7Nj/Yv9o2/1Lt8ew==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:OSh4b36LVLiqui//aZyiGEKKvlGpFGuc6q5lIZSqAfDoB6XB,iv:+nvUTCC+K/5AhzFkdxRoygFWbz3U99nTLMWEdFvrGTA=,tag:S9rokQXmW9DmZ1ftCmbcZA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:7YFQ8nr+vwCDHQ==,iv:KhsKWWoiXhQfzXhNUJmhSIthauNAkHrjhHo3FO6j4rg=,tag:ZZc0xnmppeYS2PKEctJ+fg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWFJSeTdxWWZFcE1FNVZn
            a1kvcXBDT1BaelV4YnVLVktMU2VtU3A1WVRvCkh6MUUzMlR3VDFYekdOai8wM0lq
            N2VtZjQ0MVd2aHc4QVRyOHY0LytmdEkKLS0tIHRmLy9VK1NQa2ZYaFVWNk1tSlFI
            RnZPT255dk80VnhyTC9LUHBQU2duSU0Ky86raxtkxd+CBDCz6/Cm6ReOmaurJPrX
            H8v/urlzKqS36ZoY/3a9CTN/weAijyhWyT2CexcJJhF+ZLoYbUMGig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-13T07:54:21Z"
    mac: ENC[AES256_GCM,data:JHBckKg56PiDhrcIogXBKJiBYGsm6Vo2vM5XuGcuhoZTsfqhCBlIYIpyDwnSGL+r43dyMC66I3zj0CBeAAvAn9N6iiR8t/ehRvGyBRujvAwPAo5V7S7gqcQ8C9xuY1PsOdH3n85rPDL0RXt57Mk0hB+eAwAnVXKSBwdgD6XCmw4=,iv:elwSRzB3CpZBD/N/0BVlfeV61qyn0I/4Hp64h+ILU6A=,tag:2ox+1MGrDeY5ZdZeD6jC8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
