apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:13SGhmAhi0CZugVzsSBcKoIzpYgSVnLuevU=,iv:vq31DGLIUA+YHamvbwyMZ4u7X+26KHdUXJ1Ucd+vvhg=,tag:nvmudjN6oqaMcy2Ytnl4nw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:hoEbldOYsNF2bSa3/1o7UteiXVPZ6NbXeElIDb1feVPyZf18,iv:nc7jPdPOjK3mf9jCKYILCjpFWtXsAdVu0HFGbT8DccU=,tag:KuS9dfFP8oArUfJ8bXL7Kg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:LFfTweYrCE3nRQ==,iv:7pg0M5vbRAuY2MPZA142HM06Hi9M9BDnLagrr5zANzg=,tag:1r/DQi3umERgPaJXjX+Ixg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMaVpsNkpkbXhxT2JIM05G
            RzVGaVZwaU9Dd0t5MW9ycEszVUpLckhrUXk0CjU3NHo5QmRQd01XYUV4NGNLY3hV
            UkQ2UHhuclV0clhURkQ2NFRGVDkxZHcKLS0tIEZ4azFrUE1FMFVqZERVWFNBS0RF
            WlU2LzhMQkQ0Y1RrOGdhUDlTaDNiREkKCKa/NWMuuKZD+vdu3ibtFLO3Pt0FQQls
            gaB3l+ClIJamB3T3bt+1qd/9PA0/AxzHopiOkbcLeZ8qtKfNqZM4QQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-13T08:21:12Z"
    mac: ENC[AES256_GCM,data:6bz21AW4Vrnos1S3ZFhg+cEX9V1B+dMiEESjFr7xhP3ZxtcU3jEouO6AxxzIIXq/hVRdBIqLAhC/pnXFlFdgJSJCZrW3iTDjMO3rWAN/Ir4qmyH5bmw0I9aMJHf4Ryo3i92cKpgOmzqVnmbRDESZaHlzTwxXrBV50d8hTbBbCf0=,iv:LijeXBSOvQUFE9Er2UNlmgk2LfqsXwuGWs0J+tah6Yg=,tag:BzShVp1agi1efHf3Y7LrnQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
