apiVersion: v1
kind: Secret
metadata:
    name: plex-secret
    namespace: media
stringData:
    PLEX_CLAIM: ENC[AES256_GCM,data:/WHeg0QaN/pxd4Y1MykZuhcdrLDciDwC+40=,iv:tHi0+REY2a5X/G3CkJg7AJ+8JEQ98tEAdsD8ChfxfFo=,tag:mnFomfCULD8UoZVBdt3ZGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZSt2OERrbFJjYk5IeDhq
            MHV5S0JFdWUzUXZsVlNjbFFaQUl1YmJJMmpzCjZwSGppRTUzczh5YVpBUkl1MXZC
            TVNWODV3M0o3dWtNc1hMc2o5NG1DZUUKLS0tIHpqOS9DejJMLzh1cGVKN1dxak55
            SmFDanNRcUc1djE4bXZwM3h4YWZkVDQKemX6kxufDT2EW5uPnd+xZlDOOaLhqK9o
            y6t80DsF6RBgcNzlPaLGJR1uaIsflm6JP1SC5zoOvqdwOPV1kGrtEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-16T04:26:33Z"
    mac: ENC[AES256_GCM,data:4IJinKClRg+ovuJ+sEDRsq9oAZIhkSu0cdggj/uz+becqkpiAr1v734czxlqAcHGPyRM/8LqwY36MuTCbKMLYULr0yWewhVHi+jJX5nl5BTHSV0+BcDKSm0xVl9p88msJTplLyFCeQjhQL24g7BRmxnYYsdzXe1fM32v8gqo19g=,iv:K5c3VGT0lIseOl4GLT3vwspDAXABL4KWcW4rpBZy/Uk=,tag:jCLxzgkxDfpniMISOS3L1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: plex-restic-secret
    namespace: media
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:5KuCLAbSkszaEA0lBX6D+VygN08h3PesIKTBhbMZRR8Ja62z,iv:M0WHuzIKkOlzWWDDMeMteZFs64G2efg8DzvOB4w1c0Q=,tag:dFN7MJG650077BFXXP0sVw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:EpaF2slQFlzhAxILLQB4r0c=,iv:7QNy/Pd+JF3GrdcDf4zsXEjXKt4TXCi3UEUsbOdRF6w=,tag:aeg5Z1f7PJx1KJ9B7kH4BA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:iaJ3wRzi9OgDV5YtPqwxAw==,iv:/EeRhWhloKXgf2hIc9taW54GkubxRbJM/Hrxx31GKfc=,tag:oWn8KLtQojRsVnOIUvBzCQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:fW7ucp0AMiiD7WRlzbtR0f8XMt/aQvct6r8EEjf4fuCAFywCPCgqLQ==,iv:2FyJABIEkCxEd6rbmvWoDHUcnHA/aGAIr7XcCzn+qPk=,tag:u9G3JOSBILaHDRIo6xtiFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZSt2OERrbFJjYk5IeDhq
            MHV5S0JFdWUzUXZsVlNjbFFaQUl1YmJJMmpzCjZwSGppRTUzczh5YVpBUkl1MXZC
            TVNWODV3M0o3dWtNc1hMc2o5NG1DZUUKLS0tIHpqOS9DejJMLzh1cGVKN1dxak55
            SmFDanNRcUc1djE4bXZwM3h4YWZkVDQKemX6kxufDT2EW5uPnd+xZlDOOaLhqK9o
            y6t80DsF6RBgcNzlPaLGJR1uaIsflm6JP1SC5zoOvqdwOPV1kGrtEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-16T04:26:33Z"
    mac: ENC[AES256_GCM,data:4IJinKClRg+ovuJ+sEDRsq9oAZIhkSu0cdggj/uz+becqkpiAr1v734czxlqAcHGPyRM/8LqwY36MuTCbKMLYULr0yWewhVHi+jJX5nl5BTHSV0+BcDKSm0xVl9p88msJTplLyFCeQjhQL24g7BRmxnYYsdzXe1fM32v8gqo19g=,iv:K5c3VGT0lIseOl4GLT3vwspDAXABL4KWcW4rpBZy/Uk=,tag:jCLxzgkxDfpniMISOS3L1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
