---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-teslamate
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-nginx-external
    - name: cluster-apps-rook-ceph-cluster
    - name: cluster-apps-volsync
    - name: cluster-apps-cloudnative-pg
    - name: cluster-apps-authelia
  path: ./kubernetes/apps/default/teslamate/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: teslamate
      namespace: default
  interval: 30m
  retryInterval: 1m
  timeout: 3m
