apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
    namespace: default
type: Opaque
stringData:
    #ENC[AES256_GCM,data:DDalSA==,iv:TIy019r69QSBC+KajVl/dV07G1MdBgxN7G37dK/R2vM=,tag:O2rIWyPVkI7ZFBTwAXUmfg==,type:comment]
    PAPERLESS_DBENGINE: ENC[AES256_GCM,data:xQ/VcOWzhqS3Aw==,iv:/wGWegZtBndq8KbJjyZVtgZcJ6uizaOI+luptirvRP4=,tag:1q8bam478Hweyjf4brc9HA==,type:str]
    PAPERLESS_DBPORT: ENC[AES256_GCM,data:L2mcaA==,iv:t0nG7yVZtj4JMUF9coBpul6j89f2iuK7fj59lfXXdQ4=,tag:lwk9OKtWhCRVA1iiw0OyVw==,type:str]
    PAPERLESS_DBNAME: ENC[AES256_GCM,data:BnDXGJCZWZdV,iv:hvE4KDMbetkkHZNJQ7MiQ/o/mWj3IDqS7W9EoRwWxnc=,tag:nZqVxY6QrjW9aCPg+gLzLA==,type:str]
    PAPERLESS_DBHOST: ENC[AES256_GCM,data:8lFqiGNDmHxZ026AO97E1M4hpaLN0AiULertbRZwNKo5EoVASp0Y9JWc,iv:7cMfOd8Yud6wl0OO2sBh2Vc+PcwM9qoBEq4ZE/NUf1c=,tag:LzQXoGgn3DkGbm4PaK0N2g==,type:str]
    PAPERLESS_DBUSER: ENC[AES256_GCM,data:KLbkBko=,iv:SjE82tRJ+mwQvu6rZQ9nXiwq4SyBih+3A4j1EYjGLUc=,tag:CGPtPdIygK8kzRKSXujT5g==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:naYKWfRDWQ==,iv:sQPmaAvuwqKT5Tk7s85DGHdGzUSLcEMomLYCgs1qfGY=,tag:aFjfY0MRC7hY0uKiif8iQA==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:652C/rE=,iv:9XOm9NwlHNPUm/aMNES/7L2/f+811BnLRnnxUJYzII4=,tag:aJehRwmzHcFLQ+VtSF4VPw==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:Z8z2FLQd5g==,iv:rnB7AHOc57mqLGRKteW7GZ+1P+wQdtJ6zkW1BgCX3eY=,tag:hqoFohs6rILsag5v7jZt0w==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:dNiffLPmT3jq129WUSf9nIKRUdl5EDouwxP1X2fbhr2f+Df9ZzzGOGEJAjoekVa6wInPcmdqkoiSn9JG,iv:d1CK2g4JaemTBYT/myRGbuWm/L+Cfrgdg0yW306Tj9I=,tag:i2kDhKELXH/7wlRZqJfjVA==,type:str]
    #ENC[AES256_GCM,data:FvRIYAA2zIkA0+mo0Mg=,iv:sp0rRPwIGUvuavBn3DKXg4iTT2xBNjc4uobM36/57FA=,tag:4c+Jj1eIZ+p9o1Um6Ccemw==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:lCO5reOJaWO+,iv:vtLLRy2N90HRJ8jxNGcw/Q8z5UPRS28iPuc18GgZ8jY=,tag:QDdkTPh9qJwF1Er4SeBQow==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:uKhLJQgnU9MVy+4ZkJMUalnThXOd4VZ4QGGdg+kOj9hsd7+sz/Tjdn1h,iv:ZwdrZIUE74fW7YyEcpWtYQOO7PDnBWQq/RRRyWjtkzc=,tag:xHW0i4zNTbl4sHherhrPyg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:r7GMjEo=,iv:Z7T6dg8b92gsvEuVJue/V87f8MsDFFHUkGiKgR30yx8=,tag:Vql1nqrgQ4OPUGWpB1j0Wg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:IEUOgSBstw==,iv:3UciKKeT1YnyxNrjTU2Wc2DhzgCdLqDsChPPeqtFZ68=,tag:U+g0aEMTRIrU05mev8tWTg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:0rVvhyP4GA==,iv:feGRqRFMrEbPF5SPwb7YEv9NA2prs4sm1198dkVIhfg=,tag:gRjgKIVmcUGt+5OCExzKZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4anlFL2FHdE1BR0tBVkR6
            eEUvd1g5d0MvNFd3MnVWN0pOekFZUE90dHhFCk8zK1NrN1BVSEJUdHAvd011MENC
            VS96VTJveGdMVmNWS0xQdFdaWGNsQTQKLS0tIDVuYTh4Snlqa3F3M2dJc1ZKOCsx
            ODR1WGltSjNGVTVPR0FjdnYzOFdQeXcKTnencq6IX5Jp6u+5R+PDdCIuIYp33cOG
            XFv7m+EjZpzfLPfPs8ugRm07Wh4ZJjWiG9/WvtTcoNbqxyzNmHNjUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-28T11:17:49Z"
    mac: ENC[AES256_GCM,data:z6c6DRs5j7zFvrJFUYkNwvdzToKtasMZz+/Ldqi0l0QSOBnyYSklCfVRmr7VCkRys2141Rn4H/QXfmzQL0Hwzd+Ov1Ib0/dMKJquHl8Bm/i4jYtfoXcUH9PJhWpZdiNVDSnz311KavNfuLkfdjG3h3VprLnbHrLs6z6vtXbKwXM=,iv:m6wAxOhKI9skppn+W/iUBcAveihnk3/OBtmCGVm5Jlk=,tag:7v8eyGNgSjcvRBQ/6Q+bzQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
