apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant-externalsecret
  namespace: default
spec:
  target:
    name: home-assistant-externalsecret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        HASS_POSTGRES_URL: |-
          postgresql://{{ .db_username }}:{{ .db_password }}@postgres-v15-rw.database.svc.cluster.local:5432/{{ .db_name }}
        POSTGRES_DB: |-
          {{ .db_name }}
        POSTGRES_HOST: |-
          postgres-v15-rw.database.svc.cluster.local
        POSTGRES_SUPER_PASS: |-
          {{ .superpass }}
        POSTGRES_USER: |-
          {{ .db_username }}
        POSTGRES_PASS: |-
          {{ .db_password }}
  data:
    - secretKey: db_username
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 1a994140-e20f-4462-ab52-b0aa00c70202
        property: db_username
    - secretKey: db_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 1a994140-e20f-4462-ab52-b0aa00c70202
        property: db_password
    - secretKey: db_name
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 1a994140-e20f-4462-ab52-b0aa00c70202
        property: db_name
    - secretKey: superpass
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 3fa652da-740c-427e-839a-b0aa009ef6fc
        property: superpass

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant-restic-externalsecret
  namespace: default
spec:
  target:
    name: home-assistant-restic-externalsecret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        RESTIC_REPOSITORY: |-
          {{ .restic_url }}/home-assistant
        RESTIC_PASSWORD: |-
          {{ .restic_password }}
        AWS_ACCESS_KEY_ID: |-
          {{ .aws_key_id }}
        AWS_SECRET_ACCESS_KEY: |-
          {{ .aws_secret_access_key }}
  data:
    - secretKey: restic_url
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 95b1ea75-dcab-4233-be2f-b0aa00c42f8e
        property: restic_url
    - secretKey: restic_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 95b1ea75-dcab-4233-be2f-b0aa00c42f8e
        property: restic_password
    - secretKey: aws_key_id
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: cf22cba5-8c5f-4fa6-afbc-b0aa00c4786e
        property: aws_key_id
    - secretKey: aws_secret_access_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: cf22cba5-8c5f-4fa6-afbc-b0aa00c4786e
        property: aws_secret_access_key
