---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#  - config-pvc.yaml
#  - externalsecret.yaml
  - secret.sops.yaml
  - helm-release.yaml
  - configuration.yaml
  - volsync.yaml
