apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secret
    namespace: home-automation
type: Opaque
stringData:
    HASS_POSTGRES_URL: ENC[AES256_GCM,data:k+uOU8vbX0Gr/xzgSugTwk2i34aZPIj05AoQlhc47LK2QUvsTwZ6VRzWn1sGaG1sF5VdeU0DCMB/MGVfc6jBHpOqEnOP6woqvbusPj8sXRvYbcXZ,iv:3sS9Cn1+uSWJ8tgvkkd/47ekgK53rpmNCqD+k3kWK/8=,tag:+8CaVuyMo/5oEmg8xopFrQ==,type:str]
    #ENC[AES256_GCM,data:KUGHNgAZWy6E2l/OZqc=,iv:eZ/bdZlRepRtvoKPuSQMYiao/CF7uVwFSWSsR9+pl44=,tag:4ePsVJ6e6knyGrj746EtiA==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:KsTq9OkOrPwRZaVshPM=,iv:T6Ej+RT3ZDcZzn22IWzz1hvHgFDB814x3pKBIzamtCg=,tag:oG0ixj1Dh+0yXiQcs84Aow==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:gGQxVNDGZwKI4LCRghUzKLQvpfLNdEqc0y5puS1enip5QNEZ6E6y5tT4,iv:lfrck4maW1a2GeD6GjdttipNvokgunmNicijcTIEl3U=,tag:1ZSOeW0jSwqY5nFbN34qbg==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:cZz6l8nDtg==,iv:OO9c5VxE1iPinmYmfXz89rolBrxdjuQCrGv/+QfAUFY=,tag:rrqgZC7m75qbSpKYEJrrQg==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:3KZyAFOMWw==,iv:LNvUetfATFzzYWITJp99MY2UuIhBtUUrPiYdJrhJ2vU=,tag:sqpsQFFtO5Z0JZ9E5ypZBA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:+cRaTVQ=,iv:TfumPKHPwIDahzUCN4lmcBKv0rpOD7CAvUOPMo3kiEc=,tag:p5nUXhHLGvveEQNKP1zSgg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIK0RPWC9XQ3hzaFR0L2Z5
            Rm40QXhrdGxLNEd2alNYM2hrRmR1RnRPSkdJCnBUdkZCcmcyYWcrYm15SngwU05w
            NFNFeExRT1Y5UjNHaXkwQ1BqUm1aRFEKLS0tIGQrSkg0Y1hYK0ZnVG9tRVprRUkx
            Vzc4N0hVeEJsNlhsdk00cktTaE5UVDAKCjaj+WO80DIFZAc3RJnKs5aZ3WoZ9cab
            BRmhjbV7YAPyUUHF4BVgdJzBMh89xTr2oIfWZTNkzff+HikawTm1tA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-16T04:26:33Z"
    mac: ENC[AES256_GCM,data:J0yAOri1XWfOWHOO3f/2emmOtvVA6yHlIV2SDBgb4GCURW36Fg/Fq79sbt4UNc/hRlK84K2KDT3TVC9F5SXj2UqECLdkxyJmfllDtqTbnjJhxZE7whB0R+J5OyVXxfUzkT1KvmUGXUgHo2L8bac+COtNAcVA1m9UAnwKYlS7L+A=,iv:phV8Mu+CvjG7E7kMVpdVM7FkYccpFGkyX/6X/k5BDDk=,tag:gVYOclhDzVwBXCXkr8U3zg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
