---
# yaml-language-server: $schema=https://kubernetes-schemas.thesteamedcrab.com/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: phpmyadmin
  namespace: database
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: phpmyadmin
      version: 17.0.7
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system

  values:
    ingress:
      enabled: true
      ingressClassName: internal
      path: /
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/appName: "PHP MyAdmin (MySQL)"
        hajimari.io/icon: mdi:database
        hajimari.io/group: database
        hajimari.io/instance: "admin"
      hostname: phpmyadmin.${SECRET_DOMAIN}
