apiVersion: v1
kind: Secret
metadata:
    name: mealie-secret
    namespace: default
type: Opaque
stringData:
    POSTGRES_SERVER: ENC[AES256_GCM,data:hTLag1LAjJEOViEA7H92BmoLHg74Eo2t438Ls3wQgTK7FtWfQSM5fSb0,iv:1Y4l3J5+IrTLACyLR7ESPsjz87BInH9aAzjwEuCZaZE=,tag:HAtzILkuTunlqnninvol2w==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:18ufNA==,iv:merQJd9600djinVNPGRpEFhe4fEvdEWScSBM8i78MPM=,tag:fgoRgDh4EjYBv+sx9BkP9A==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:NLL6IJWZoA==,iv:+EnrnEqK1IeF4Dy608Cv7eIkyQNXlwDuKsk+ECpKrjI=,tag:wFaXd/q3Lllre4ZXlIbPaA==,type:str]
    #ENC[AES256_GCM,data:nThfJB0g2WamvHK2La0=,iv:ny5jiRaSdcZH4M4PaG/Od5wGj3+EWCm+qA09pFgYfYA=,tag:akaEb0ha9dqsM1RFI/mweQ==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:4h3CdAgp,iv:spKY+u6fDB+SIhY/3Ropk1szXvsrFR3V1z7Xozz5JYc=,tag:uA/qCzNLFBd3PwemVfXPQA==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:Qbg+76WkoQDkyuY9axQxTUIzagbODEHl9W0Rv0oWOZVkhVyU1ET0Eq7r,iv:4UHYiM4oYbFIeiLAEK8NLGh3uISp9G2/sWbc/+Y0VzA=,tag:aJiKUJHJcYX+4Cs0Ssbkcw==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:7uzO0Q3fQA==,iv:ha11NKyidVppvpA/A/LPNrJVDYs5okl1r+yFVZzbJFE=,tag:I7oNpd/Cr0FEBc68qca6wA==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:MEBgY79Zqw==,iv:22mnKJDer8xZlLoEuJ6qpocuKXL8Z9wNVjoAUccCxAc=,tag:Ri9Aybs9XYO+ZKAz8MXgJw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:b4OCDZw=,iv:CizNmgr5AcIfMGq/OlFGrrCyHFOezwYqmYuxmwMNexo=,tag:Uvkpr+DmoIb9vMiFxtSFcA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZW91ZmJlemNDbzA0QWc4
            Nk5NNGxZWURJWWZub0Zac2poOC9wYmJ0ZDJVCmY1ZDJTaE0vZUpzRUh4OFB2UnJn
            Mm5sS1F5VzR3cW1kcjZWVTlkalhJaWcKLS0tIEVTa3VjeEJzd0QzY3A5UzA4MjVE
            c2c5Y2sveSszYldZNXFKQnh4OXdSVUUK6eeQ9B80gJBAjqLPoq5/Qc67X19gsWvW
            zM+4DUaRPt4zxYMWpn8VL8AlHEoH29LlGlVAXlZl4zGC5YXQOhq6GA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-16T04:26:32Z"
    mac: ENC[AES256_GCM,data:o1osvUrhNaBseHPTHqPU1NjmprcMA/gdIWMfm1wvI3WJqJ1RauUyBgNStW+PIV3Mc6HHiPl+znv4zRnLLjcubIfteA0YcnlAUFcslQWAOpr+Wzh2z86UfvkL1KmXspofcLhoP/8Y8KAXP1GWu+6rkURjO+4lJ1ScjAts5yWcvYg=,iv:3gIpQLIdeil95EM0sstYY84G1R2aqJAUrj/wkgthxsc=,tag:y/NWyMOiOV2hvUMym9P2wQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: mealie-restic-secret
    namespace: default
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:cAWexw9Gk5hklnLawfNTKP/mbaM/EXKMu4uE21Mvt/1JdloteA4=,iv:8a3TOYE1paRGca2q6Y6t4dCHhs9XYPeFMmYP7CIRHHU=,tag:5Fq2OmhH2T23raFlu7kRVQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:q+IQOpGQJyWmAhY6UyRauiU=,iv:DqiJwSLJ4vAWAV1+e+ZPhWvbVtmZC5lcyvB6aj+TULU=,tag:duLBUB5Gq1G1l+riBicbjA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:gLjECeQ/rX8tZa6x+0pWwA==,iv:cAFVvBr5I82uJSUSL/KWPQptrOmoHAq21Gc61zhANnE=,tag:uqRq8T3snq6KnBUCgRygxg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:uYpwrfFhCg/wzlMDOlKbyZixBEXuKIJZEqVCYB+3xtfS4rHS6elD0A==,iv:IIf9XF/lfl311BrQbB3oSmHEKDaJTaHNyoZsrvFSwfA=,tag:eAwT5cxf+VdEe7t0SuuVzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZW91ZmJlemNDbzA0QWc4
            Nk5NNGxZWURJWWZub0Zac2poOC9wYmJ0ZDJVCmY1ZDJTaE0vZUpzRUh4OFB2UnJn
            Mm5sS1F5VzR3cW1kcjZWVTlkalhJaWcKLS0tIEVTa3VjeEJzd0QzY3A5UzA4MjVE
            c2c5Y2sveSszYldZNXFKQnh4OXdSVUUK6eeQ9B80gJBAjqLPoq5/Qc67X19gsWvW
            zM+4DUaRPt4zxYMWpn8VL8AlHEoH29LlGlVAXlZl4zGC5YXQOhq6GA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-16T04:26:32Z"
    mac: ENC[AES256_GCM,data:o1osvUrhNaBseHPTHqPU1NjmprcMA/gdIWMfm1wvI3WJqJ1RauUyBgNStW+PIV3Mc6HHiPl+znv4zRnLLjcubIfteA0YcnlAUFcslQWAOpr+Wzh2z86UfvkL1KmXspofcLhoP/8Y8KAXP1GWu+6rkURjO+4lJ1ScjAts5yWcvYg=,iv:3gIpQLIdeil95EM0sstYY84G1R2aqJAUrj/wkgthxsc=,tag:y/NWyMOiOV2hvUMym9P2wQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
