---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-jdownloader
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: 'true'
spec:
  dependsOn:
    - name: cluster-apps-rook-ceph-cluster
    - name: cluster-apps-nginx-external
  path: './kubernetes/apps/media/jdownloader/app/'
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: jdownloader
      namespace: media
