---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./configmap.yaml
  - ./helmrelease.yaml
  - ./cluster_role.yaml
  - ./service_account.yaml
  - ./service_account_token.yaml
  - ./secret.sops.yaml
  - ../../../../templates/gatus/guarded
