#jinja2: trim_blocks: True, lstrip_blocks: True
apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
stringData:
    HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: ENC[AES256_GCM,data:kjsmoeCIUjyZSUPThIYauTT1ZEGoD06u08NZzB0GT+k=,iv:RsSrUVnBMd0cJ8rd8khbWN6DXJcvaJjCP+Dqe+UJaV4=,tag:k+jj7pMZhWEQ+AjCfXJ5GQ==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: ENC[AES256_GCM,data:/O/aSSZImH1N4bGdFAB36cNWWJcfe+GRHFCCVuWOfPlABoKt,iv:W3iH9n0FACdnPhfVr7Vfql/gS+klKGh7vUO3wll5S1Q=,tag:+YnI5B2vC0uXk4D5Cec0jw==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: ENC[AES256_GCM,data:PKvAYJ8l7qGsqr3Je/bKGbZuzmQWwo+RkapLC6yq4H1pnA3so4/ZPw==,iv:G9mDboZfS9JMSnEGQ8Xp70W2b+V0DfSkLahw6VoZnrY=,tag:K52AVNpaKrrLoMxTeP8F+Q==,type:str]
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:XMD66+0=,iv:bKfXl8jNcHJ6DM2jEX2W8v8rwWQabXWvTx+T2SY0kyA=,tag:u6qzoktmbqy5AcBM9AJA/Q==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:T0RvaaUW3g==,iv:1qhcDeCFTDrRYbRpOl+yYic+l1PJBG7wQ8JgvWXrY6A=,tag:srm0i0FT+8Wh+HNq7Of/iw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoL0FtRVArMkNEZzVwVnZ3
            Z1hZTmpiV1BoTVg0KytLYlFsSUtrVnZ5ejFFCjA2RlJCQnk5WG5YRGwwRWllMysw
            Z0Evd0s1djlINndqU0dNVE1UNm5meGMKLS0tIFlhZjR6bGZ6ajBSSmlObVJPckM5
            TUtzaENMVERSbTFqMmdvMUROMWEzNVEKitMLz0zg7yGtR0vNVxF5Wwq7nQbSsCtB
            C9C5w79eyG4rmFVYJtABCQyI1tu+zqpp0JdsO15eUz9Kl0KvafRChQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-26T12:16:39Z"
    mac: ENC[AES256_GCM,data:g2eDQ1dYWQ8/R5r+Hl9oUkQRL9SZ57ryINaEwsoh1csA6BQTrGu8xy1r/vf4EBsRpr2/D5Djkzha3PANCPj1zRX3XVddYXwyGY39TSlqNZr/3f856VaGnyvL22KjPovgJi6ZbJMyzw/4QInrF0K7Hml2KBFcSWTOPQaPa5yz/Uc=,iv:jc2n50dINkFhoCf4My13Fh/JuF4GLjp4KArwgSkcetU=,tag:ybQ1+aJcOdJvfqPJV4J6Gg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
