#jinja2: trim_blocks: True, lstrip_blocks: True
apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
stringData:
    HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: ENC[AES256_GCM,data:BNuNurBPY4LF+CVX5L29RK8lmSnuUpzXoA1xZDP1vg4=,iv:p2cHLO6b4/IyUeZrOqY+pHmNqzMGBzkIugPg0ZD8bWw=,tag:SnnJ6t0WIw68+Y4wtQVx+g==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: ENC[AES256_GCM,data:F5EoC5tu1xtaVLQtqiXpW6Zm2io070qexSZp3OihfkIYQL1X,iv:ysTRAHUhfdSqfITJzpxUWPcZ5zrwt89DAqhJwvQsgMk=,tag:5L/qfQeGoiOXYQu1tZkqDw==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: ENC[AES256_GCM,data:EkCmAnpaM+vzVZKeaygvQOo5jQBj1u4TDQyissektJgHuBiB7Ece1w==,iv:zOXlkWKfDSrQE/8SFh2tegOwf6dCWTzHKbd6RGF3W2Q=,tag:lt83qsgGdqC8wcKwe8pQDA==,type:str]
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:PzW0Q54=,iv:vfKs/+UbyztjRzLdx4wM9nxCSnKm3YL/XNnFFBSLves=,tag:3yRGZZtI2AxaZNq7BkpHHQ==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:Hbc85B+pgw==,iv:3ux8l3ZTeEYbIDZKgerpAh+A4uLgfYl1fB6tHQnavH0=,tag:m3QqP5zQ8Sl/s4A1deeTtg==,type:str]
    HOMEPAGE_VAR_SECRET_DOMAIN: ENC[AES256_GCM,data:qT4pz+AxykCixQ==,iv:lEeaDBzUeAsBvrq6pHEET/eQuOnzot4NCR0JNow11do=,tag:ev0pHJsaCgIX8gQwRHTAtg==,type:str]
    HOMEPAGE_VAR_LATITUDE: ENC[AES256_GCM,data:FIdIWVxuYJdBkg==,iv:vqvSHcoWwy8GkuyleTQG3PDEmKMGzpEQA1+1SUPJg00=,tag:bwQj6Erilhvg50K6N202og==,type:str]
    HOMEPAGE_VAR_LONGITUDE: ENC[AES256_GCM,data:jfK/zwQPvnKqeg==,iv:qc5ICz81XXJP7Q2uh2BfCyLRGGkzZ15229NzkyWp36g=,tag:DH5P8lFfWiHmGPibFuk9IQ==,type:str]
    HOMEPAGE_VAR_PROXMOX_TOKEN_ID: ENC[AES256_GCM,data:Pv4qUQ98/aBp56zHYDeMWs0=,iv:/1lKUywkOxrO+fZbODbizcDzqVHdisnsEGy58+etU2s=,tag:g4vtogZCqBdbdCW+CWuSow==,type:str]
    HOMEPAGE_VAR_PROXMOX_TOKEN_SECRET: ENC[AES256_GCM,data:Ejp05izaQ0Pn2ii1APQawZKRibPVUDNtpeD1zSNJLHJ8R2Xg,iv:tGe8etAgBTm+18QadFAd28P8jOc9P20gzlKWSGun+Dc=,tag:NAmOyUVzbhI5VjknKF1hew==,type:str]
    HOMEPAGE_VAR_TRUENAS_TOKEN: ENC[AES256_GCM,data:2opz8T/IAVC0yYVUGNLfYMImO5jJFXcgKrPXpa0DNIRbB7NX6A8j22PJh62bFx30rzXkOwkw1TUY71decWtJTPV6,iv:aoedsnueJCna5rxXH+rCIdTi6s9/1orfpZ7RwXVlniY=,tag:k6g7pM7GELUTGX/mc2wV4Q==,type:str]
    HOMEPAGE_VAR_HASS_TOKEN: ENC[AES256_GCM,data:3plGj1UkkuFY1JAiOsiIvJhEnG8k2dsFLEJ2lVayWMFhl8f8HvXZOGj1/BkgTgbKLW04jFuI+Pdp8ks2FJ8VPkxawzX2Ia4PKfFCv7JMBEbpHldCpVmT6hLXJKgACiA6ZwQ+LPC10hNr/PKDZxci3uAwBXDBR0DDRO4N+lqGs545tX6EcuGW7xj6OPfDIpt92nVhGTcSSp7b6HG3Is+wi4VuTnwsdW/nbTpWe+yNoemYwdMSKNoc,iv:L2yHpYwv1DH+ZHLamdHl8TTvraYGt9BHoCwGcyYwwcA=,tag:C5hWZ9eutWZhfelcBRCKww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlL0tDM1gza2pqWkMyMFNX
            U3BpRTdmdnJBYVJ2czdxT0MyQzNzMlZ0YTBRCmZYRm5RMUtPSnRzc09lNGU3dDF5
            RzJxbldobitvQ09nZ0RJQXVoMWpBbTQKLS0tIEErZllSS1VtRTJGRlFJWE1sdGFy
            MElQRW4zMllaUUJQNHp0QkxzTSt3S1UKZdWylMyvmJuwfL288IxhXlkOHUMLZUe8
            VLcBpi1EOCq8FXLfK/BCxV6v7bGFUQrxfywRn40ELEoG3vRx+FWbcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-27T09:34:23Z"
    mac: ENC[AES256_GCM,data:1JaUVaxgOY+gn+piKCvzpGADUosvHuEO8L2gfJ/vcIeEPpVptWlCTYZS80Dt0fJxb9KfKSi6nlABSlKIBPyl9d4v/7V9aRYOmVqmtkZ0t8qIcE7z3yTs6DNOCUGABUt2bMQepZOIbtgyXVPcbHNFgUcYeFmkmvaAtl0ClJtsyWk=,iv:v+tetPMqCV7WHgcuuSxxGpCyi0n32FhO478nJM1GAio=,tag:oUyyDekT6bOaggMehdrL4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
