#jinja2: trim_blocks: True, lstrip_blocks: True
apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
stringData:
    HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: ENC[AES256_GCM,data:zGanfsWdCE2zq1BrbfSfFyDNeqF4t9Ao2etV9Fo7um8=,iv:EvDid3uLh5YsDjKnMHrD5F6GnyBxfENP3xGvRqcN0oY=,tag:zC/d5+Y82DL7eDCML7L+6g==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: ENC[AES256_GCM,data:t1ABUQ4Cknhqo1W2OGF7oNlctYBGkaIhwj3g2ziL01ELzCuF,iv:wEj+EDkiZDKZJSXw0AYm/J/0hoizx2gzrBcpY/QJxcE=,tag:ekExlanZT1eGFo2bh/keDQ==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: ENC[AES256_GCM,data:X1L2ApIVmdJ/9Yp7HIJ18UddKtqiUHHS9XOrD+/dTQqyNzfWegXVgQ==,iv:E5+DxW7pl9HIxuzE4LoNb12SiirDrYtuWmcxzZLXLFA=,tag:+re92S9KYYj/Uz/vDIvfqQ==,type:str]
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:HJMll/I=,iv:xQ6oGOPde7whLzW1gcqwCqXK30ybjRcYbufRc6z2R6A=,tag:bWzJhQ5HJOOWoGKQG75b3Q==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:Qbu79CPrPA==,iv:ZZ1AKtmgNJNmQYsenJqY13rs13h/K+fanbk6zA2LMz4=,tag:8Om7iGONT8AdiIZxocQskQ==,type:str]
    HOMEPAGE_VAR_SECRET_DOMAIN: ENC[AES256_GCM,data:IO5xyn1XHXM3XA==,iv:nCmH6TsAUohJOhvrEuH4+vVF2LAlqAMXy7W8TOoslJs=,tag:+9t1cQkD8KUf1D/WKJlEiA==,type:str]
    HOMEPAGE_VAR_LATITUDE: ENC[AES256_GCM,data:ewLMxslJi58rHA==,iv:MORzS5wLd5ctSpsiyKMUsoK79uDZLLUhogquF+7JDjk=,tag:ykNTYz/u35T+SEvasC8wBA==,type:str]
    HOMEPAGE_VAR_LONGITUDE: ENC[AES256_GCM,data:aOYo/zGo8nw2qQ==,iv:DMbFKz1fQdMpY8zg9ZAhNA5e9p4Ok+ddh0izVWJ2EX4=,tag:MU5yRABH21p6q8NIco9siA==,type:str]
    HOMEPAGE_VAR_PROXMOX_URL: ENC[AES256_GCM,data:geZVHBZCZxqPapR1P17oC0+fjBhR7A==,iv:oQ72nCh/ko4kmcekhQwOjKke5xFbvl9TXaCv+7ODIag=,tag:nlcm7ClrRODcDsuKwi99+A==,type:str]
    HOMEPAGE_VAR_PROXMOX_TOKEN_ID: ENC[AES256_GCM,data:5HwBeUReYbcENMl0Vij7sw==,iv:mnSpArAMyESexN5rotgMxFuB2rN1JF5ZsV7TtCoeKCw=,tag:9Uc07ML4Rk+DgEG+rkmekg==,type:str]
    HOMEPAGE_VAR_PROXMOX_TOKEN_SECRET: ENC[AES256_GCM,data:OdNqR9HV+HsnSG3Vq0lmCAoA/Oak7mz1WEAZPxFC+sKtrcWa,iv:cmz186DQv3CqwwYVOw5eAdZ/m4UoQOUqramFJd6c6k4=,tag:c7Y55Lum/gCNKhENN+1iHQ==,type:str]
    HOMEPAGE_VAR_TRUENAS_TOKEN: ENC[AES256_GCM,data:WBPN3I97rcc3RYtG8SGB8Wd5Lq8lwUpBfgQuC3kuLjHtpjYfvHPq2XtZ1fd7lMB8d32eTzxeaI4SYUNniMgsRW65,iv:PjMVG4s612HQHbG78oqVnagz016qcey26L6JQlfd2NA=,tag:Mow+rtU0hGMT5v7bYidEWw==,type:str]
    HOMEPAGE_VAR_HASS_TOKEN: ENC[AES256_GCM,data:fFYD8DFX7jgUw5jOk5mQFtmzKT2ZLZJ5CsZvLhw10qTpykhSg7TUbql48IcMKQnYYY59qd04Rr+ofYjT2J6T5iMpkH+RH7LJ5C+/XHNX5hxy2Z8aQvX7XH497miyZP1t/MAKFz2aAF7zpza5dmE88Jogc9btxooPuCqD96Sk6bRIvzGe1OphKxQn9fc0QYDLxX6R3P4Nal4y0Xg7i4ZlnNpZ++mGMRmmZvH35D056JykvRsFSt+p,iv:0a4piSAgawpj3ny8W604K+sWvTIxbxhL4fL1cFytUqM=,tag:K/QZk6bTVCYhC174bU0fxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRTRQQlNyL2RDSmxaekpl
            dC9Wd0NKeUZaQzRIQldFeWw4T0RCa2VJUGxRClNMb1ZXMW1rWjRBcWFlc3dRbmJu
            T1RXLzFBc2h5Z0hwNmpFeW1qNGU2MVEKLS0tIGlydHNXTk85QTQ2eTNYWHpIVjgx
            THZOSVlBNk16cWlzQ2hLWnozVkp6MmMKfIbedw9XN6FdfTGO1+LnN37iU0POf1W6
            gF32q/bPirx2IARRlAF/85JOTPqsboXZawiX83b1ONtQ/2l2EJyC3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-03T08:06:05Z"
    mac: ENC[AES256_GCM,data:guLViE8Og7gHZaUtTLwaJFsNqmoVhOYLoza1VJtU4FdN5PxcIyeAg7TJFTekER/C6Xoq5cJdxr9MsclMh7iTvLhU8V5RkRb0EWgwpY6HUDhs4Hvhs+4Qhw2McEKYftu06VjlN2yCwk5GHNJ2B9YZPg8LG0xAJanIXyHi00vjfDw=,iv:VGdv5qEBVafGDx8wcklZNK0LDwNrPMjlr5/bp4KY+6s=,tag:DWZki/GlaG43uzuqZN8FiA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
