#jinja2: trim_blocks: True, lstrip_blocks: True
apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
stringData:
    HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: ENC[AES256_GCM,data:jCG73YqPGeVPjWuM7zNxc0HozNAs2TizqZMSrfb+wzI=,iv:K0t2/DWvMwJQs8oZH86oxZ++1vLbftWHkAxlPkSL2G0=,tag:UTmJBXMKboFPGgaUAUVneQ==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: ENC[AES256_GCM,data:pM/sFs3DNFvyjJdxqb9AOSXa5hpwYw6pRlfxYYpwn6DDFkFZ,iv:wjSBkwVCghZ4XnYB+jqgMlujHFQv+oVHj8hzN99VT70=,tag:D+YfXKyO/9sMT6AZ0UWMrA==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: ENC[AES256_GCM,data:ycmxdk/jV+fCIX6XYZo3cRXf1zrMliKgsv9jL8qnNMt0F9e5CUnmNA==,iv:0OzvO0ujOm9boaKI5ePOYKJRjpiz7PM0ELmDGGqoCSI=,tag:7vCQW8i0cXhrVi0veYbN3g==,type:str]
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:yZ144kg=,iv:IZfNv1MIKLFnehVa2M9yG8deWiD3irx1zVxnDhOxhcs=,tag:l7TNOR3TcDCvP+ubOTxfQQ==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:LM+pQlCWBg==,iv:IYcedQ7ovK58nE/YxLr0RsId5iCfLRlQf17esjb6k0Y=,tag:foLxAA8B3f5XPJy6wgPpUg==,type:str]
    HOMEPAGE_VAR_SECRET_DOMAIN: ENC[AES256_GCM,data:WRnY9xgaiu32HQ==,iv:WxxdBc1um7g7wGVBYrLEzjwSBQBFX2HJPXDbJmkUJ00=,tag:g3aWsS44ApJ5MZ21F82TNA==,type:str]
    HOMEPAGE_VAR_LATITUDE: ENC[AES256_GCM,data:xCb2331wskdSvg==,iv:uMh5mgKiKBuXlBq5AcK7TThUlruB4GTHioyXTACudc0=,tag:kU1VDuu1l+BoXpgf93NNoA==,type:str]
    HOMEPAGE_VAR_LONGITUDE: ENC[AES256_GCM,data:HXWYhc1uMOsyZw==,iv:fVSASco3qmE5r1kkzw4BLIQcEFWRINjIU6QNfWTEEmE=,tag:ZpU4HYH04o8Pnowcq2+tYg==,type:str]
    HOMEPAGE_VAR_PROXMOX_URL: ENC[AES256_GCM,data:Ql3YjPpIkM35mW89PFdFiO0kzEuyjw==,iv:MoCqOItv8ciM2ep7qRMK8yS6FNRMLHkESXeaaiOqHGI=,tag:fXQb/MEw6P5O+J7BrLwVUw==,type:str]
    HOMEPAGE_VAR_PROXMOX_TOKEN_ID: ENC[AES256_GCM,data:q0zvkOTbxj0SVPAbLPHIQA==,iv:EpZ2bVMteg9rkh7vkxOQT1YCpfJFCntjiBy/MhDD6fQ=,tag:gQyAQv8lHTiw0IJZvBup+A==,type:str]
    HOMEPAGE_VAR_PROXMOX_TOKEN_SECRET: ENC[AES256_GCM,data:UTI6wuHfyLP9w72hh7g6GvgVM2WtvyTrAHSNi65pDEERWjQu,iv:LNhY3FQSya9XutBCrNGmvj4vrGHMp0NHKHb4P33pS7Y=,tag:CRnj9veHUOd7oa3ZNdP8YQ==,type:str]
    HOMEPAGE_VAR_TRUENAS_TOKEN: ENC[AES256_GCM,data:yxddN1iRAeL9p+9AM3jJz1Zarc0tVi9KB5LZ73MSASK/6m9VFboHsJRR0fFdwUUjuerVPDRa2+SWqMYOljYPpgDh,iv:85qAMqZUKN9DouItvp4VPwwKytPHh45r4P+Ba0cBW9E=,tag:oTYOHtlWYVdh++4dhhgXXw==,type:str]
    HOMEPAGE_VAR_HASS_TOKEN: ENC[AES256_GCM,data:BhU2GvPd6yAlaHF8t0uSYGvmdzD/BKNLllfRBRkFwcMeA0TbLPTTVCd2gJTRCGec+vXM7j9dOlX0a1DyjTzt//f657cnx2cpMSXXWZpm+dsjDTW7rBfUhFxMchDSvbcBfJcCZRJNpMwxTDT53S+AQ4zfR4mB+r2kngYlMeL0Xpbd1Ev7WlzXl107pzHOJKEUhBgLl/+0KiHPeyLdb3of/MJ0fmV8X8GF4xy2jerH+dMMXiEwH2Ge,iv:WpriFS37cerU5k0IbW161s8IupPk6XA08UT+6Zkmrto=,tag:ccPPtkjkRkCb78j1roGKdA==,type:str]
    HOMEPAGE_VAR_JDOWNLOADER_USERNAME: ENC[AES256_GCM,data:0NGpeCYpxMRR/fzmnqKoonT+,iv:cOzaCcvYtL5zzoDmUY5xDNKlacpd0ZuL5en5virP8cw=,tag:yjurB5mrw04UXShOz9Zn4w==,type:str]
    HOMEPAGE_VAR_JDOWNLOADER_PASSWORD: ENC[AES256_GCM,data:c0ATVONwPA==,iv:sLxZRkjD74auh25AUMhQdhUvPdvblEgUDHx9YZ5sm5g=,tag:V4O8XPiujDXALEQR49h8wA==,type:str]
    HOMEPAGE_VAR_ALSA_S3_URL: ENC[AES256_GCM,data:DoN+nGRu+A2DmXKFzbrTQbtvcuGCNnJ18gRL,iv:uJF3YK16kKbsAfz+ORK1C70PypBBbgJQhjRJfwg5Ii4=,tag:3aW4TuP/94i4d4RvLDXV0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WGdSNmNtamNtMmFxRUpI
            V1BTV1NBUzZqY0Y0dXdkSXRSR3VnWHRCZ3lVCmJHTGpxb2pqeE1LTUdxUS9FVG9n
            a1RZUEZ6c2V3aXl6L3h0Y05Yak9JUFEKLS0tIG45dWNlSlJzS3VSczNmaXJyMURl
            TU9OSDVQTHRkNWpKMDZxODhRYVJlQUUKvtV5TxLe+IahJg5JVb3LNa82D3HstIFD
            sXY1WVlak5GXwR3xe5kh/zvf+tQ2b7siPxp3VCcnIxkJDP0zJOcqPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-04T05:21:40Z"
    mac: ENC[AES256_GCM,data:/QS060n9bh4hMp/+UQUX8ZejNCGDiruP/UKq1B40DZbpwY6ZjV5ZhVfwlbqqd85f83d9/53OAfmrFLZaHV+VktQGujiO82vtWAMezuxdgMSx9TRa/TQib67XP5uuG3rrOdKMTAs0GEk9Oga2KhA9FaFbT1Q4oYrq6ruuhOQIB3k=,iv:93oxWHQFDjrLmjh1w0trqTt5H5QWtIt8YYOBMCSs+T0=,tag:iHhV1TE0Xd135oAbsUk+2w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
