apiVersion: v1
kind: Secret
metadata:
    name: frigate-secret
    namespace: default
type: Opaque
stringData:
    FRIGATE_MQTT_SERVER: ENC[AES256_GCM,data:CnZaW9g/7oxSURA+eg==,iv:sSx9VSC1FHVhbqx7Qo/UEZ6KQWnwDyfSxk6/UtpWnl4=,tag:i10q4moX6jK8cga2vvgU8A==,type:str]
    FRIGATE_MQTT_USER: ENC[AES256_GCM,data:Cy0Im/4=,iv:fBbnCERVh2YUWg6k5p/NFz1Zp9IXFiGlRTWEAGn8QdA=,tag:5id6GgIihpGSw/G4geOsNw==,type:str]
    FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:9m8pTts7x597D8M=,iv:5IxYCGR+oEn/JeJGOqJlm4prlCpGMhdHHm8IUTP65xY=,tag:XMaXtcAKGqG4TaLrKGy4rQ==,type:str]
    FRIGATE_RTSP_USER: ENC[AES256_GCM,data:IRRDxkM=,iv:oWW8bQtcSKGujUfh7LtO4xgH/3/AbkJtmYFlBB7r7TM=,tag:XTONlwRmTwUcYw3zb347ZA==,type:str]
    FRIGATE_RTSP_PASSWORD: ENC[AES256_GCM,data:v2t56TsevA==,iv:38M82iec2n+sM/O8b6wuMEcsbG5UcxsFlHu9bXGxnZc=,tag:Lxi6XFooKNv15edsuiVJBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cUJseWFFOVR4Tm5KSDlj
            emQ2TEl3eExTMzZXQS9IZmpUMUxmaG12RkRBCk9xSGZ1QXBtbTR4NENDVDhPQlpN
            WXRYUkFNdkcrTGtoYzJYWHRpa1FhalUKLS0tIGNrWlZVSVVpd1hWdHhGMXFhMnZ3
            bUVzVFlEaDBaWnJYVzRsY0xQY1RWU1kKLw0SRBizPCKmGcI+V2fUgYn1COThrH9T
            Bru/WFXu+VNy33qTAkb73fC9MR91PziIqJ6NpPaYbO/NfWbtRVW0jQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-16T04:26:32Z"
    mac: ENC[AES256_GCM,data:+Mo4qphW5MFkyfThTOi5qilOgimNrrq9+pp8ep4hl9g42hvWBJgmJzL625SRrKzDxmXR8uJW6k9lVAUNie2CILQ8p6RyU0x+93X45Hnex9czkGFl6kygkDRIFkjFTewOzQcUjcbrkXlmNdMCVVwoaB5kYkxLJ2TTWzOgVD9PsLg=,iv:dVjPp/kRjp3c7GbMCcfZF7QokhoQgaYUMmhNGgEFIlQ=,tag:4H1mXIVojwr0O1edq5aEtw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
