---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app apcupsd-exporter
  namespace: observability
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 30
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 30
  uninstall:
    keepHistory: false

  values:
    controller:
      replicas: 1
      strategy: RollingUpdate
    image:
      repository: iodeveloper/prom-apcupsd-exporter
      tag: latest@sha256:e7cd07f560691a66316b13fcbbb89b4e311e0dfacbd8472e870aeff9d6a71382
    command: ["/prom-apcupsd-exporter", "--apcupsd", "apcupsd.observability.svc.cluster.local:3551", "--collectInterval", "1"]
    env:
      TZ: Europe/Paris
    resources:
      requests:
        cpu: 15m
        memory: 64M
      limits:
        memory: 124M

    service:
      main:
        ports:
          http:
            port: 8001

    ingress:
      main:
        enabled: false

    nodeSelector:
      kubernetes.io/hostname: "worker-1"
