---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: other
resources:
  - ./secret.sops.yaml
  - ./helmrelease.yaml
  - ./volsync.yaml
commonLabels:
  app.kubernetes.io/name: epic-free-games
  app.kubernetes.io/instance: epic-free-games
