---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      adguard:
        replicas: 1
        strategy: RollingUpdate

        containers:
          app:
            image:
              repository: adguard/adguardhome
              tag: v0.107.53
            env:
              TZ: Europe/Paris

    service:
      app:
        controller: adguard
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          io.cilium/lb-ipam-ips: "192.168.1.178"
          loadBalancerIP: '192.168.1.178'
        ports:
          http:
            primary: true
            port: 3000
          dns-tcp:
            port: 53
            protocol: TCP
          dns-udp:
            port: 53
            protocol: UDP
          dns-o-h:
            port: 443
            protocol: TCP
          dns-o-tls:
            port: 853
            protocol: TCP

    persistence:
      data:
        existingClaim: adguard-data
        globalMounts:
          - path: /opt/adguardhome/data
      conf:
        existingClaim: adguard-conf
        globalMounts:
          - path: /opt/adguardhome/conf

    ingress:
      app:
        className: "internal"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
      dns-query:
        className: "external"
        hosts:
          - host: &host "dns-query.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: dns-o-h
        tls:
          - hosts:
              - *host
